//! COG decode oracle test (08-PATTERNS "committed-artifact + no-drift",
//! mirroring `envi-geo/tests/oracle_utm.rs`).
//!
//! Loads the committed `tests/fixtures/cog/*.tif` + expected-window `*.toml`
//! (generated by `tools/gis_oracle/gen_cog_fixtures.py` from **GDAL** via
//! rasterio) and asserts the pure-Rust `tiff`-crate decode path in
//! `envi_gis::cog` reproduces GDAL's windowed reads to `<= tol`, across BigTIFF,
//! float predictor-3, nodata, and padded-edge fixtures. One test per edge case;
//! a coverage assertion proves a BigTIFF case is exercised (Pitfall 1 — the
//! suite cannot pass without BigTIFF support).
//!
//! **Python/GDAL are NOT needed at test time** — the fixtures are committed data.

use envi_gis::GisError;
use envi_gis::cog::header::{self, CogHeader};
use envi_gis::cog::window::{PixelWindow, bbox_to_pixel_window, decode_window};
use envi_gis::cog::{MAX_DECODED_PX, geo_tags};
use serde::Deserialize;

const DIR: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures/cog/");

#[derive(Deserialize)]
struct Fixture {
    meta: Meta,
    #[serde(default)]
    case: Vec<Case>,
}

#[derive(Deserialize)]
struct Meta {
    fixture: String,
    #[serde(default)]
    bigtiff: bool,
    tol: f64,
    #[serde(default)]
    origin_x: f64,
    #[serde(default)]
    origin_y: f64,
    #[serde(default)]
    pixel_size_x: f64,
    #[serde(default)]
    pixel_size_y: f64,
    #[serde(default)]
    has_nodata: bool,
    #[serde(default)]
    nodata: f64,
}

#[derive(Deserialize)]
struct Case {
    name: String,
    col_off: u32,
    row_off: u32,
    win_width: u32,
    win_height: u32,
    /// Row-major expected values; `nan` marks an expected hole (nodata).
    samples: Vec<Vec<f64>>,
}

fn load_toml(name: &str) -> Fixture {
    let text = std::fs::read_to_string(format!("{DIR}{name}"))
        .unwrap_or_else(|e| panic!("fixture TOML {name} must exist: {e}"));
    toml::from_str(&text).unwrap_or_else(|e| panic!("fixture TOML {name} must parse: {e}"))
}

fn load_tif(name: &str) -> Vec<u8> {
    std::fs::read(format!("{DIR}{name}"))
        .unwrap_or_else(|e| panic!("fixture {name} must exist: {e}"))
}

fn win(c: &Case) -> PixelWindow {
    PixelWindow {
        col_off: c.col_off,
        row_off: c.row_off,
        width: c.win_width,
        height: c.win_height,
    }
}

/// Decode every case in a fixture and compare against the GDAL-read expected
/// values, including the window geotransform (proves geometry is read from the
/// IFD, never assumed — T-08-02-04).
fn assert_fixture_matches(toml_name: &str) -> Meta {
    let fx = load_toml(toml_name);
    let bytes = load_tif(&fx.meta.fixture);

    for c in &fx.case {
        let raster = decode_window(&bytes, win(c), MAX_DECODED_PX)
            .unwrap_or_else(|e| panic!("{}: decode failed: {e:?}", c.name));

        assert_eq!(
            (raster.width, raster.height),
            (c.win_width as usize, c.win_height as usize),
            "{}: window dims mismatch",
            c.name
        );

        // Geotransform of the window: origin shifted to (col_off, row_off).
        let exp_ox = fx.meta.origin_x + f64::from(c.col_off) * fx.meta.pixel_size_x;
        let exp_oy = fx.meta.origin_y + f64::from(c.row_off) * fx.meta.pixel_size_y;
        assert!(
            (raster.geo.origin_x - exp_ox).abs() < 1e-6
                && (raster.geo.origin_y - exp_oy).abs() < 1e-6,
            "{}: window origin {:?} != expected ({exp_ox}, {exp_oy})",
            c.name,
            (raster.geo.origin_x, raster.geo.origin_y),
        );
        assert_eq!(
            raster.geo.pixel_size_x, fx.meta.pixel_size_x,
            "{}: psx",
            c.name
        );
        assert_eq!(
            raster.geo.pixel_size_y, fx.meta.pixel_size_y,
            "{}: psy",
            c.name
        );

        for (r, row) in c.samples.iter().enumerate() {
            for (col, &expected) in row.iter().enumerate() {
                let got = raster.get(col, r);
                if expected.is_nan() {
                    assert_eq!(
                        got, None,
                        "{}: pixel ({col},{r}) expected a hole (nodata), got {got:?}",
                        c.name
                    );
                } else {
                    let v = got.unwrap_or_else(|| {
                        panic!(
                            "{}: pixel ({col},{r}) expected {expected}, got a hole",
                            c.name
                        )
                    });
                    assert!(
                        (f64::from(v) - expected).abs() <= fx.meta.tol,
                        "{}: pixel ({col},{r}) = {v} vs expected {expected} (tol {})",
                        c.name,
                        fx.meta.tol,
                    );
                }
            }
        }
    }
    fx.meta
}

#[test]
fn bigtiff_fixture_decodes_against_gdal() {
    // Coverage (Pitfall 1): the fixture is genuinely BigTIFF — magic II+\0.
    let bytes = load_tif("ahn_bigtiff.tif");
    assert_eq!(
        &bytes[0..4],
        &[0x49, 0x49, 0x2B, 0x00],
        "ahn_bigtiff.tif must be BigTIFF (magic 49 49 2B 00)"
    );
    let meta = assert_fixture_matches("ahn_bigtiff.toml");
    assert!(meta.bigtiff, "coverage: a BigTIFF case must be exercised");
}

#[test]
fn predictor3_deflate_fixture_decodes_with_iff_geotransform() {
    // Classic TIFF, DEFLATE + float predictor 3, non-square non-nominal pixels.
    let bytes = load_tif("glo30_predictor3.tif");
    assert_eq!(
        &bytes[0..4],
        &[0x49, 0x49, 0x2A, 0x00],
        "glo30_predictor3.tif must be classic TIFF (magic 49 49 2A 00)"
    );
    let meta = assert_fixture_matches("glo30_predictor3.toml");
    // The geotransform must be the non-nominal one from the IFD, not a square
    // 1/3600 assumption (Pitfall 5): pixel_size_x != |pixel_size_y|.
    assert_ne!(
        meta.pixel_size_x,
        meta.pixel_size_y.abs(),
        "predictor-3 fixture must have non-square pixels (proves IFD-read geometry)"
    );
}

#[test]
fn nodata_samples_become_holes_not_zero() {
    let fx = load_toml("nodata_edge.toml");
    assert!(fx.meta.has_nodata && fx.meta.nodata == -9999.0);
    let bytes = load_tif("nodata_edge.tif");
    let c = fx
        .case
        .iter()
        .find(|c| c.name == "over-nodata 6x6")
        .expect("over-nodata case present");
    let raster = decode_window(&bytes, win(c), MAX_DECODED_PX).expect("decode ok");

    let mut saw_hole = false;
    for (r, row) in c.samples.iter().enumerate() {
        for (col, &expected) in row.iter().enumerate() {
            if expected.is_nan() {
                saw_hole = true;
                // The load-bearing property: nodata is a hole, never a silent 0.0.
                assert_eq!(
                    raster.get(col, r),
                    None,
                    "nodata pixel ({col},{r}) must be a hole"
                );
                assert_ne!(raster.get(col, r), Some(0.0));
            }
        }
    }
    assert!(saw_hole, "the over-nodata case must contain nodata cells");
}

#[test]
fn edge_tile_padding_is_cropped() {
    // The padded-edge window lands inside tiles that are padded beyond
    // ImageWidth/Length; the decoder must crop to the valid data (stride =
    // chunk_data_dimensions, not the nominal tile width) — a wrong stride would
    // panic on an out-of-range index. Reaching the oracle compare proves it.
    let fx = load_toml("nodata_edge.toml");
    let bytes = load_tif("nodata_edge.tif");
    let c = fx
        .case
        .iter()
        .find(|c| c.name == "padded-edge 8x8")
        .expect("padded-edge case present");
    let raster = decode_window(&bytes, win(c), MAX_DECODED_PX).expect("edge decode ok");
    for (r, row) in c.samples.iter().enumerate() {
        for (col, &expected) in row.iter().enumerate() {
            let v = raster.get(col, r).expect("edge sample present");
            assert!((f64::from(v) - expected).abs() <= fx.meta.tol);
        }
    }
}

#[test]
fn oversized_window_is_rejected_before_decode() {
    // The bomb declares 2048x2048 px in its IFD but is a few KB on disk. A full
    // window with a small budget must be rejected from the IFD-derived pixel
    // count BEFORE any read_chunk allocates the ~16 MB raster (threat
    // T-08-02-01). The error variant, returned without OOM, is the evidence.
    #[derive(Deserialize)]
    struct BombMeta {
        width: u32,
        height: u32,
    }
    #[derive(Deserialize)]
    struct Bomb {
        meta: BombMeta,
    }
    let text = std::fs::read_to_string(format!("{DIR}bomb.toml")).expect("bomb.toml exists");
    let bomb: Bomb = toml::from_str(&text).expect("bomb.toml parses");
    let bytes = load_tif("bomb.tif");
    let full = PixelWindow {
        col_off: 0,
        row_off: 0,
        width: bomb.meta.width,
        height: bomb.meta.height,
    };
    let budget = 4096;
    let result = decode_window(&bytes, full, budget);
    assert!(
        matches!(
            result,
            Err(GisError::DecodeBudgetExceeded { requested_px, limit })
                if requested_px == (bomb.meta.width as usize) * (bomb.meta.height as usize)
                    && limit == budget
        ),
        "expected DecodeBudgetExceeded from IFD dims, got {result:?}"
    );
}

#[test]
fn window_out_of_bounds_is_rejected_not_padded() {
    // A window reaching past ImageWidth/Length is a typed error, never a
    // silently padded raster (Pitfall 7 / T-08-02-03).
    let bytes = load_tif("ahn_bigtiff.tif");
    let over = PixelWindow {
        col_off: 60,
        row_off: 44,
        width: 8, // 60 + 8 = 68 > width 64
        height: 8,
    };
    let result = decode_window(&bytes, over, MAX_DECODED_PX);
    assert!(
        matches!(result, Err(GisError::WindowOutOfBounds { .. })),
        "expected WindowOutOfBounds, got {result:?}"
    );
}

#[test]
fn zero_extent_window_is_rejected() {
    let bytes = load_tif("ahn_bigtiff.tif");
    let zero = PixelWindow {
        col_off: 0,
        row_off: 0,
        width: 0,
        height: 4,
    };
    assert!(matches!(
        decode_window(&bytes, zero, MAX_DECODED_PX),
        Err(GisError::WindowOutOfBounds { .. })
    ));
}

#[test]
fn bbox_to_pixel_window_selects_center_covered_pixels() {
    // Drive the source-CRS bbox -> pixel-window bridge over a real fixture's
    // IFD geotransform, then confirm decoding that window reproduces GDAL.
    let bytes = load_tif("ahn_bigtiff.tif");
    let mut dec = header::open(&bytes).unwrap();
    let hdr: CogHeader = header::read_header(&mut dec).unwrap();
    let geo = geo_tags::read_geotransform(&mut dec).unwrap();

    // Ask for a 4x4 block starting at pixel (8, 12) via pixel-center coords.
    let (col_off, row_off, w, h) = (8u32, 12u32, 4u32, 4u32);
    let (min_x, top_y) = geo.pixel_to_map(f64::from(col_off) + 0.5, f64::from(row_off) + 0.5);
    let (max_x, bot_y) = geo.pixel_to_map(
        f64::from(col_off + w - 1) + 0.5,
        f64::from(row_off + h - 1) + 0.5,
    );
    // psy < 0 => top_y > bot_y; bbox min_y/max_y ordering.
    let pw =
        bbox_to_pixel_window(&geo, &hdr, min_x, bot_y, max_x, top_y).expect("bbox covers pixels");
    assert_eq!(
        pw,
        PixelWindow {
            col_off,
            row_off,
            width: w,
            height: h
        },
        "bbox center-inclusion must recover the intended pixel window"
    );
}
