//! Source registry as data (D-04): the pluggable GIS-source table.
//!
//! # Module I/O
//! - **Inputs:** a WGS84 lon/lat query [`Bbox`] (the import viewport), or a
//!   [`SourceId`] string.
//! - **Output:** a [`SourceDescriptor`] selection per layer — terrain (AHN4 DTM
//!   where a real kaartblad covers the viewport, GLO-30 DSM everywhere else), land
//!   cover (WorldCover), and buildings (OSM Overpass) — plus the committed AHN
//!   kaartblad index ([`AHN_INDEX_TOML`], parsed by [`ahn_index`]).
//! - **Invariant (load-bearing):** the registry is **pure data**. A new national
//!   DTM slots in later as a `SourceDescriptor` row plus a coverage polygon — no
//!   control-flow change (08-RESEARCH Pattern 3, D-04).
//! - **Invariant (load-bearing, DATA-01):** a national DTM is selected only when it
//!   can actually deliver — [`terrain_source`] gates on the coarse coverage hull
//!   **and** on at least one intersecting kaartblad in the committed index. A
//!   viewport inside the hull with no covering tile (an index gap, a coastal sliver)
//!   therefore falls back to **GLO-30**, which is global, rather than planning zero
//!   terrain tiles. The descriptor and the tile plan are resolved from the SAME
//!   test, so the CRS / CORS mode / DSM ("surface model") badge TS reads from the
//!   descriptor always match the tiles it is handed.
//!
//! # CORS capability (D-02)
//! Each descriptor carries its verified [`Cors`] mode (08-RESEARCH §Per-Source
//! CORS Capability Map, live-probed): AHN and Overpass are browser-**Direct**;
//! GLO-30 and WorldCover have no `Access-Control-Allow-Origin` and MUST route
//! through the same-origin byte proxy (**Proxy**).

use envi_geo::{LonLat, RdNewCrs};
use geo::{Contains, LineString, MultiPolygon, Point, Polygon};
use std::sync::OnceLock;

use crate::GisError;

/// The committed AHN kaartblad tile index (tile name ↔ RD New bbox), embedded at
/// compile time. Generated by `tools/gis_oracle/gen_ahn_index.py` from the PDOK
/// ATOM feed and committed with a DO-NOT-EDIT + sha256 provenance banner
/// (08-PATTERNS committed-artifact pattern).
///
/// It is the **COMPLETE** grid (~1373 kaartbladen), not a sample: it is both the
/// tile-name lookup AND — through [`ahn_tiles_for`] — the authoritative coverage
/// test. A partial index is therefore not a smaller-but-correct artifact, it is a
/// silent hole in national coverage (an earlier 9-tile "representative subset"
/// left Amsterdam with no terrain tile at all).
pub const AHN_INDEX_TOML: &str = include_str!("registry/ahn_index.toml");

/// Browser CORS reachability of a source (D-02 capability map).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Cors {
    /// Fetched cross-origin directly from the browser (server sends `ACAO`).
    Direct,
    /// No CORS headers — routed through the same-origin allowlisted byte proxy.
    Proxy,
}

/// The GIS data kind a source provides.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SourceKind {
    /// Bare-earth digital terrain model (e.g. AHN4).
    Dtm,
    /// Digital surface model — includes vegetation/roofs (e.g. GLO-30).
    Dsm,
    /// Land-cover raster (e.g. ESA WorldCover).
    Landcover,
    /// Vector building footprints (e.g. OSM Overpass).
    Buildings,
}

/// A stable, human-readable source identifier (`"ahn4-dtm"`, `"glo30"`, ...).
pub type SourceId = &'static str;

/// A WGS84 lon/lat bounding box (min/max **degrees**). The import viewport.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct Bbox {
    /// Western edge, degrees east.
    pub min_lon: f64,
    /// Southern edge, degrees north.
    pub min_lat: f64,
    /// Eastern edge, degrees east.
    pub max_lon: f64,
    /// Northern edge, degrees north.
    pub max_lat: f64,
}

impl Bbox {
    /// The bbox center `(lon, lat)`.
    #[must_use]
    pub fn center(&self) -> (f64, f64) {
        (
            (self.min_lon + self.max_lon) / 2.0,
            (self.min_lat + self.max_lat) / 2.0,
        )
    }
}

/// The geographic reach of a source, in WGS84.
pub enum Coverage {
    /// Available everywhere (e.g. GLO-30, WorldCover, Overpass).
    Global,
    /// A national/regional coverage hull (e.g. the AHN Netherlands hull).
    Region(MultiPolygon<f64>),
}

impl Coverage {
    /// Whether the query `bbox` is served by this coverage — a deterministic
    /// point-in-polygon test on the bbox center (never a silent default).
    #[must_use]
    pub fn covers(&self, bbox: &Bbox) -> bool {
        match self {
            Coverage::Global => true,
            Coverage::Region(mp) => {
                let (lon, lat) = bbox.center();
                mp.contains(&Point::new(lon, lat))
            }
        }
    }
}

/// A single registry row: everything needed to fetch and attribute a source.
///
/// Fields follow 08-RESEARCH Pattern 3. `coverage` gates selection; `crs` is the
/// source's native CRS (the terrain reprojection boundary consumes it); `cors`
/// is the verified D-02 reachability; `license`/`attribution` feed the D-11
/// provenance stamp and the SC5 map attribution.
pub struct SourceDescriptor {
    /// Stable identifier (`"ahn4-dtm"`, `"glo30"`, `"worldcover"`, `"osm-overpass"`).
    pub id: SourceId,
    /// The data kind this source provides.
    pub kind: SourceKind,
    /// Geographic reach in WGS84.
    pub coverage: Coverage,
    /// Native CRS EPSG label (`"EPSG:28992"` RD New, `"EPSG:4326"` WGS84).
    pub crs: &'static str,
    /// How tiles/queries are addressed (`"kaartblad"`, `"1deg"`, `"bbox-query"`).
    pub tile_scheme: &'static str,
    /// The fetch URL template (TS fills the `{...}` slots; this crate never fetches).
    pub endpoint_template: &'static str,
    /// Verified browser CORS reachability (D-02).
    pub cors: Cors,
    /// SPDX-ish license tag for the provenance stamp.
    pub license: &'static str,
    /// Human-readable attribution string (SC5 map credit).
    pub attribution: &'static str,
}

/// The AHN Netherlands coverage hull, WGS84.
///
/// A **coarse** bounding hull of the Dutch mainland + Wadden extent. It is only
/// the cheap first gate ("could AHN plausibly serve this?"); the authoritative
/// test is an actual kaartblad in [`AHN_INDEX_TOML`] ([`terrain_source`] requires
/// BOTH). Vertices trace the national outline closely enough to exclude
/// neighbouring capitals (Brussels/Paris/Berlin/London).
fn nl_coverage() -> MultiPolygon<f64> {
    // (lon, lat) ring, closed, tracing the NL outline coarsely.
    let ring = LineString::from(vec![
        (3.36, 51.30),
        (3.36, 53.62),
        (5.20, 53.62),
        (7.23, 53.30),
        (7.23, 52.00),
        (6.02, 51.75),
        (6.22, 51.36),
        (5.65, 50.75),
        (5.80, 51.05),
        (4.55, 51.42),
        (3.90, 51.20),
        (3.36, 51.30),
    ]);
    MultiPolygon::new(vec![Polygon::new(ring, vec![])])
}

/// Build the static registry table (four sources). Lazily initialised because
/// [`Coverage::Region`] carries a non-`const` [`MultiPolygon`].
fn build_registry() -> Vec<SourceDescriptor> {
    vec![
        SourceDescriptor {
            id: "ahn4-dtm",
            kind: SourceKind::Dtm,
            coverage: Coverage::Region(nl_coverage()),
            crs: "EPSG:28992",
            tile_scheme: "kaartblad",
            endpoint_template: "https://service.pdok.nl/rws/actueel-hoogtebestand-nederland/atom/downloads/dtm_05m/{tile}.tif",
            cors: Cors::Direct,
            license: "CC0-1.0",
            attribution: "AHN (Actueel Hoogtebestand Nederland), PDOK — CC0",
        },
        SourceDescriptor {
            id: "glo30",
            kind: SourceKind::Dsm,
            coverage: Coverage::Global,
            crs: "EPSG:4326",
            tile_scheme: "1deg",
            endpoint_template: "https://copernicus-dem-30m.s3.amazonaws.com/Copernicus_DSM_COG_10_{ns}_00_{ew}_00_DEM/Copernicus_DSM_COG_10_{ns}_00_{ew}_00_DEM.tif",
            cors: Cors::Proxy,
            license: "Copernicus-Free",
            attribution: "Copernicus DEM GLO-30 © ESA / Copernicus (credit required)",
        },
        SourceDescriptor {
            id: "worldcover",
            kind: SourceKind::Landcover,
            coverage: Coverage::Global,
            crs: "EPSG:4326",
            tile_scheme: "3deg",
            endpoint_template: "https://esa-worldcover.s3.eu-central-1.amazonaws.com/v200/2021/map/ESA_WorldCover_10m_2021_v200_{tile}_Map.tif",
            cors: Cors::Proxy,
            license: "CC-BY-4.0",
            attribution: "ESA WorldCover 2021 v200 — © ESA WorldCover, CC BY 4.0",
        },
        SourceDescriptor {
            id: "osm-overpass",
            kind: SourceKind::Buildings,
            coverage: Coverage::Global,
            crs: "EPSG:4326",
            tile_scheme: "bbox-query",
            endpoint_template: "https://overpass-api.de/api/interpreter",
            cors: Cors::Direct,
            license: "ODbL-1.0",
            attribution: "© OpenStreetMap contributors (ODbL)",
        },
    ]
}

/// The process-wide source registry (built once).
#[must_use]
pub fn registry() -> &'static [SourceDescriptor] {
    static REG: OnceLock<Vec<SourceDescriptor>> = OnceLock::new();
    REG.get_or_init(build_registry)
}

/// Look up a descriptor by its [`SourceId`], or `None` if unknown.
#[must_use]
pub fn source(id: SourceId) -> Option<&'static SourceDescriptor> {
    registry().iter().find(|d| d.id == id)
}

// --- AHN kaartblad index (committed artifact, no runtime toml dep) -----------

/// One AHN kaartblad row: the tile name and its RD New (EPSG:28992) bbox.
#[derive(Debug, Clone, PartialEq)]
pub struct AhnTile {
    /// Kaartblad name (`"M_25GN1"`) — the `{tile}` slot of the AHN endpoint.
    pub name: String,
    /// RD New western edge, meters.
    pub min_x: f64,
    /// RD New southern edge, meters.
    pub min_y: f64,
    /// RD New eastern edge, meters.
    pub max_x: f64,
    /// RD New northern edge, meters.
    pub max_y: f64,
}

/// Parse the committed [`AHN_INDEX_TOML`] into kaartblad rows with a tiny
/// hand-rolled line reader — NO `toml`/`serde` runtime dependency (the
/// dep-quarantine banner stays intact; the parse is pure over an `include_str!`ed
/// blob, WASM-safe). The format is regular: `[[tile]]` opens a row, then
/// `name = "M_.."` + four `rd_*` floats. The `[meta]` table and any
/// malformed/partial row are skipped (never a panic on data).
fn parse_ahn_index() -> Vec<AhnTile> {
    let mut tiles = Vec::new();
    let mut name: Option<String> = None;
    let mut min_x: Option<f64> = None;
    let mut min_y: Option<f64> = None;
    let mut max_x: Option<f64> = None;
    let mut max_y: Option<f64> = None;

    let flush = |tiles: &mut Vec<AhnTile>,
                 name: &mut Option<String>,
                 min_x: &mut Option<f64>,
                 min_y: &mut Option<f64>,
                 max_x: &mut Option<f64>,
                 max_y: &mut Option<f64>| {
        // `take()` clears every field regardless; a complete row is pushed, an
        // incomplete one is simply dropped (its fields already reset to `None`).
        if let (Some(n), Some(a), Some(b), Some(c), Some(d)) = (
            name.take(),
            min_x.take(),
            min_y.take(),
            max_x.take(),
            max_y.take(),
        ) {
            tiles.push(AhnTile {
                name: n,
                min_x: a,
                min_y: b,
                max_x: c,
                max_y: d,
            });
        }
    };

    for raw in AHN_INDEX_TOML.lines() {
        let line = raw.trim();
        if line.starts_with('#') || line.is_empty() {
            continue;
        }
        if line.starts_with('[') {
            // A new table (`[[tile]]` or `[meta]`) closes the current row.
            flush(
                &mut tiles, &mut name, &mut min_x, &mut min_y, &mut max_x, &mut max_y,
            );
            continue;
        }
        let Some((key, value)) = line.split_once('=') else {
            continue;
        };
        let (key, value) = (key.trim(), value.trim());
        match key {
            "name" => name = Some(value.trim_matches('"').to_string()),
            "rd_min_x" => min_x = value.parse().ok(),
            "rd_min_y" => min_y = value.parse().ok(),
            "rd_max_x" => max_x = value.parse().ok(),
            "rd_max_y" => max_y = value.parse().ok(),
            _ => {}
        }
    }
    // Flush the final row (the file does not end on a new table header).
    flush(
        &mut tiles, &mut name, &mut min_x, &mut min_y, &mut max_x, &mut max_y,
    );
    tiles
}

/// The committed AHN kaartblad index, parsed once (the full ~1373-tile grid).
#[must_use]
pub fn ahn_index() -> &'static [AhnTile] {
    static INDEX: OnceLock<Vec<AhnTile>> = OnceLock::new();
    INDEX.get_or_init(parse_ahn_index)
}

/// The kaartbladen whose RD bbox intersects the WGS84 viewport `bbox`.
///
/// Empty when the viewport lies outside the AHN grid — **or** when the RD
/// reprojection fails (a failure can never masquerade as coverage; the caller
/// falls back to the global GLO-30 source rather than planning nothing).
#[must_use]
pub fn ahn_tiles_for(bbox: Bbox) -> Vec<&'static AhnTile> {
    let Ok((min_x, min_y, max_x, max_y)) = reproject_bbox_to_rd(bbox) else {
        return Vec::new();
    };
    ahn_index()
        .iter()
        .filter(|t| {
            // Closed-interval AABB overlap.
            t.min_x <= max_x && t.max_x >= min_x && t.min_y <= max_y && t.max_y >= min_y
        })
        .collect()
}

/// Reproject a WGS84 viewport to an axis-aligned RD New (EPSG:28992) bbox by
/// transforming its four corners and taking the extent (sterea is near-conformal
/// over NL, so the corner extent bounds the reprojected rectangle). Reprojection
/// is the single `envi_geo` boundary (GEOX-04).
///
/// # Errors
/// [`GisError::Reproject`] if the RD-New reprojection of any corner fails.
pub(crate) fn reproject_bbox_to_rd(bbox: Bbox) -> Result<(f64, f64, f64, f64), GisError> {
    let crs = RdNewCrs::new().map_err(|e| GisError::Reproject {
        message: e.to_string(),
    })?;
    let mut min_x = f64::INFINITY;
    let mut min_y = f64::INFINITY;
    let mut max_x = f64::NEG_INFINITY;
    let mut max_y = f64::NEG_INFINITY;
    for (lon, lat) in [
        (bbox.min_lon, bbox.min_lat),
        (bbox.min_lon, bbox.max_lat),
        (bbox.max_lon, bbox.min_lat),
        (bbox.max_lon, bbox.max_lat),
    ] {
        let p = crs
            .to_rd(LonLat {
                lon_deg: lon,
                lat_deg: lat,
            })
            .map_err(|e| GisError::Reproject {
                message: e.to_string(),
            })?;
        min_x = min_x.min(p.x_m);
        min_y = min_y.min(p.y_m);
        max_x = max_x.max(p.x_m);
        max_y = max_y.max(p.y_m);
    }
    Ok((min_x, min_y, max_x, max_y))
}

/// The terrain source for `bbox`: AHN4 DTM where a real kaartblad covers the
/// viewport, GLO-30 DSM everywhere else (D-04 AHN-preferred, GLO-30 fallback).
///
/// The coarse coverage hull is only the cheap gate; the **authoritative** test is
/// [`ahn_tiles_for`] — AHN is chosen only when the committed index actually
/// resolves a tile, so a hull-interior gap falls back to the global GLO-30 DSM
/// (flagged `SourceKind::Dsm` — the surface-model badge, DATA-01) instead of
/// yielding an empty terrain plan.
///
/// # Panics
/// Never in practice — the two terrain descriptors are compile-time table rows.
#[must_use]
pub fn terrain_source(bbox: Bbox) -> &'static SourceDescriptor {
    let ahn = source("ahn4-dtm").expect("ahn4-dtm is a registry row");
    if ahn.coverage.covers(&bbox) && !ahn_tiles_for(bbox).is_empty() {
        ahn
    } else {
        source("glo30").expect("glo30 is a registry row")
    }
}

/// A per-layer import plan for a viewport: which source feeds terrain, land
/// cover, and buildings.
pub struct ImportPlan {
    /// Terrain source (AHN4 or GLO-30 by coverage).
    pub terrain: &'static SourceDescriptor,
    /// Land-cover source (WorldCover).
    pub landcover: &'static SourceDescriptor,
    /// Buildings source (OSM Overpass).
    pub buildings: &'static SourceDescriptor,
}

/// Select every layer's source for a WGS84 viewport `bbox` (D-04 coverage lookup).
#[must_use]
pub fn plan(bbox: Bbox) -> ImportPlan {
    ImportPlan {
        terrain: terrain_source(bbox),
        landcover: source("worldcover").expect("worldcover is a registry row"),
        buildings: source("osm-overpass").expect("osm-overpass is a registry row"),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A small bbox around Dam Square, Amsterdam — inside AHN coverage.
    fn amsterdam() -> Bbox {
        Bbox {
            min_lon: 4.88,
            min_lat: 52.36,
            max_lon: 4.91,
            max_lat: 52.38,
        }
    }

    /// A bbox in the North Sea, WEST of the Dutch coast: inside the coarse
    /// coverage hull, but the AHN grid has no kaartblad there (it maps land).
    fn north_sea() -> Bbox {
        Bbox {
            min_lon: 3.54,
            min_lat: 52.49,
            max_lon: 3.56,
            max_lat: 52.51,
        }
    }

    /// A small bbox around Berlin — well outside AHN coverage.
    fn berlin() -> Bbox {
        Bbox {
            min_lon: 13.36,
            min_lat: 52.50,
            max_lon: 13.42,
            max_lat: 52.53,
        }
    }

    #[test]
    fn registry_lists_the_four_expected_sources_with_verified_cors() {
        let ids: Vec<_> = registry().iter().map(|d| d.id).collect();
        assert_eq!(ids, ["ahn4-dtm", "glo30", "worldcover", "osm-overpass"]);

        // D-02 CORS capability map (live-probed): AHN + Overpass Direct;
        // GLO-30 + WorldCover Proxy.
        assert_eq!(source("ahn4-dtm").unwrap().cors, Cors::Direct);
        assert_eq!(source("osm-overpass").unwrap().cors, Cors::Direct);
        assert_eq!(source("glo30").unwrap().cors, Cors::Proxy);
        assert_eq!(source("worldcover").unwrap().cors, Cors::Proxy);
    }

    #[test]
    fn nl_interior_bbox_selects_ahn4_dtm_non_nl_selects_glo30_dsm() {
        // NL interior → AHN4 DTM.
        let t = terrain_source(amsterdam());
        assert_eq!(t.id, "ahn4-dtm");
        assert_eq!(t.kind, SourceKind::Dtm);

        // Outside NL → GLO-30 DSM (flagged Dsm — surface model, D-05 badge).
        let t = terrain_source(berlin());
        assert_eq!(t.id, "glo30");
        assert_eq!(t.kind, SourceKind::Dsm);
    }

    #[test]
    fn plan_selects_worldcover_and_overpass_for_every_viewport() {
        let p = plan(amsterdam());
        assert_eq!(p.terrain.id, "ahn4-dtm");
        assert_eq!(p.landcover.id, "worldcover");
        assert_eq!(p.landcover.kind, SourceKind::Landcover);
        assert_eq!(p.buildings.id, "osm-overpass");
        assert_eq!(p.buildings.kind, SourceKind::Buildings);

        // Landcover/buildings are global — same picks outside NL.
        let p = plan(berlin());
        assert_eq!(p.terrain.id, "glo30");
        assert_eq!(p.landcover.id, "worldcover");
        assert_eq!(p.buildings.id, "osm-overpass");
    }

    #[test]
    fn coverage_hull_excludes_neighbouring_capitals() {
        // Brussels, Paris, London are outside the NL hull → GLO-30.
        for (lon, lat) in [(4.35, 50.85), (2.35, 48.85), (-0.13, 51.51)] {
            let bbox = Bbox {
                min_lon: lon - 0.01,
                min_lat: lat - 0.01,
                max_lon: lon + 0.01,
                max_lat: lat + 0.01,
            };
            assert_eq!(
                terrain_source(bbox).id,
                "glo30",
                "({lon}, {lat}) must fall back to GLO-30"
            );
        }
    }

    #[test]
    fn ahn_index_carries_do_not_edit_banner_and_sha256_provenance() {
        let first = AHN_INDEX_TOML.lines().next().unwrap();
        assert!(
            first.contains("DO NOT EDIT"),
            "index must open with the DO-NOT-EDIT banner, got: {first}"
        );
        assert!(
            AHN_INDEX_TOML.contains("sha256:"),
            "index must carry a sha256 provenance line"
        );
    }

    /// REGRESSION: a viewport inside the coverage hull but with NO kaartblad must
    /// fall back to the global GLO-30 **DSM** (the surface-model badge, DATA-01) —
    /// never to AHN-with-zero-tiles, which is what emptied the terrain plan.
    #[test]
    fn hull_interior_without_a_kaartblad_falls_back_to_glo30_dsm() {
        let bbox = north_sea();
        let ahn = source("ahn4-dtm").unwrap();
        assert!(
            ahn.coverage.covers(&bbox),
            "the coarse hull does cover this point — that is the whole trap"
        );
        assert!(
            ahn_tiles_for(bbox).is_empty(),
            "but no kaartblad maps the open sea"
        );

        let t = terrain_source(bbox);
        assert_eq!(t.id, "glo30", "must fall back to the global source");
        assert_eq!(t.kind, SourceKind::Dsm, "flagged as a surface model");
    }

    #[test]
    fn committed_index_is_the_full_kaartblad_grid_not_a_subset() {
        // The full AHN DTM 0.5 m grid the PDOK ATOM feed publishes is ~1373
        // kaartbladen. A "representative subset" (the old artifact held 9) leaves
        // most of the Netherlands — Amsterdam included — with no tile at all.
        let tiles = ahn_index();
        assert!(
            tiles.len() > 1_000,
            "index must be the full grid, got {} tiles",
            tiles.len()
        );
        for t in tiles {
            assert!(t.name.starts_with("M_"), "AHN name: {}", t.name);
            // Every kaartblad is exactly 5000 m x 6250 m in RD New.
            assert!((t.max_x - t.min_x - 5000.0).abs() < 1e-6, "{}", t.name);
            assert!((t.max_y - t.min_y - 6250.0).abs() < 1e-6, "{}", t.name);
        }
    }

    #[test]
    fn amsterdam_centre_resolves_the_kaartblad_that_actually_covers_it() {
        // The exact viewport of the failing in-browser import.
        let bbox = Bbox {
            min_lon: 4.894,
            min_lat: 52.363,
            max_lon: 4.914,
            max_lat: 52.373,
        };
        let names: Vec<&str> = ahn_tiles_for(bbox)
            .iter()
            .map(|t| t.name.as_str())
            .collect();
        assert_eq!(names, ["M_25GN1"], "Amsterdam centre is kaartblad M_25GN1");
        assert_eq!(terrain_source(bbox).id, "ahn4-dtm");
    }

    #[test]
    fn ahn_index_parses_and_tiles_have_ordered_rd_bboxes() {
        // The committed artifact is valid TOML with well-formed RD bboxes.
        let doc: toml::Value = toml::from_str(AHN_INDEX_TOML).expect("ahn_index.toml parses");
        let tiles = doc
            .get("tile")
            .and_then(toml::Value::as_array)
            .expect("has [[tile]] entries");
        assert!(!tiles.is_empty(), "index has at least one tile");
        for t in tiles {
            let name = t.get("name").and_then(toml::Value::as_str).unwrap();
            assert!(name.starts_with("M_"), "AHN tile name: {name}");
            let min_x = t.get("rd_min_x").and_then(toml::Value::as_float).unwrap();
            let max_x = t.get("rd_max_x").and_then(toml::Value::as_float).unwrap();
            let min_y = t.get("rd_min_y").and_then(toml::Value::as_float).unwrap();
            let max_y = t.get("rd_max_y").and_then(toml::Value::as_float).unwrap();
            assert!(
                max_x > min_x && max_y > min_y,
                "{name} bbox must be ordered"
            );
        }
    }
}
