"""Generate the committed UTM reprojection oracle fixture.

Writes ``crates/envi-geo/tests/fixtures/oracle/utm_landmarks.toml`` — a
cross-implementation reference the pure-Rust ``envi-geo`` crate (proj4rs) is
tested against. Ground truth is **pyproj** (the C PROJ library), so the fixture
pins proj4rs's ``etmerc`` transverse Mercator against the reference PROJ
implementation to <= 1e-3 m.

Regeneration is operator-driven (``python gen_utm.py``); the TOML is committed
and **Python/pyproj are NOT build or test dependencies** — the Rust test reads
the committed data only.

Provenance: the fixture header records a sha256 of this generator so a fixture
can be traced to the exact oracle that produced it.
"""

from __future__ import annotations

import hashlib
import math
from pathlib import Path

from pyproj import Transformer

# ~10 world-spread landmarks: both hemispheres, near-equator, high latitude,
# and the lon = 179.9 zone-60 edge. (name, lon_deg, lat_deg).
LANDMARKS = [
    ("Dam Square, Amsterdam", 4.8936, 52.3731),
    ("Sydney", 151.2093, -33.8688),
    ("Quito", -78.4678, -0.1807),
    ("Anchorage", -149.9003, 61.2181),
    ("Cape Town", 18.4241, -33.9249),
    ("Singapore", 103.8198, 1.3521),
    ("Reykjavik", -21.9426, 64.1466),
    ("Buenos Aires", -58.3816, -34.6037),
    ("Tokyo", 139.6917, 35.6895),
    ("Pacific zone-60 edge", 179.9, 0.0),
]

TOL_M = 1e-3


def utm_zone_for(lon_deg: float) -> int:
    """Plain UTM zone formula — MUST match crates/envi-geo/src/crs.rs."""
    zone = math.floor((lon_deg + 180.0) / 6.0) + 1
    return max(1, min(60, zone))


def utm_proj_string(zone: int, south: bool) -> str:
    return (
        f"+proj=utm +zone={zone}"
        f"{' +south' if south else ''} +ellps=WGS84 +units=m +no_defs"
    )


def _fmt(x: float) -> str:
    return repr(float(x))


def main() -> None:
    here = Path(__file__).resolve().parent
    root = here.parents[1]
    out = root / "crates/envi-geo/tests/fixtures/oracle/utm_landmarks.toml"
    out.parent.mkdir(parents=True, exist_ok=True)

    sha = hashlib.sha256(Path(__file__).read_bytes()).hexdigest()[:16]

    lines: list[str] = []
    lines.append("# generated by tools/crs_oracle/gen_utm.py — DO NOT EDIT")
    lines.append("# Cross-implementation CRS oracle: pyproj (C PROJ) vs proj4rs (pure Rust).")
    lines.append("# GEOX-04 / SC3: the one reprojection seam pinned to PROJ ground truth.")
    lines.append("")
    lines.append("[meta]")
    lines.append('oracle = "pyproj / C PROJ — EPSG:4326 -> +proj=utm"')
    lines.append(f'provenance = "gen_utm.py sha256:{sha}"')
    lines.append(f"tol_m = {_fmt(TOL_M)}")
    lines.append("")

    for name, lon, lat in LANDMARKS:
        zone = utm_zone_for(lon)
        south = lat < 0.0
        transformer = Transformer.from_crs(
            "EPSG:4326", utm_proj_string(zone, south), always_xy=True
        )
        easting, northing = transformer.transform(lon, lat)
        lines.append("[[case]]")
        lines.append(f'name = "{name}"')
        lines.append(f"lon_deg = {_fmt(lon)}")
        lines.append(f"lat_deg = {_fmt(lat)}")
        lines.append(f"zone = {zone}")
        lines.append(f"south = {'true' if south else 'false'}")
        lines.append(f"easting_m = {_fmt(easting)}")
        lines.append(f"northing_m = {_fmt(northing)}")
        lines.append("")

    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {out} ({len(LANDMARKS)} cases, sha256:{sha})")


if __name__ == "__main__":
    main()
