"""Generate the committed RD New (EPSG:28992) reprojection oracle fixture.

Writes ``crates/envi-geo/tests/fixtures/oracle/rd_landmarks.toml`` — a
cross-implementation reference the pure-Rust ``envi-geo`` crate (proj4rs) is
tested against for the Dutch RD New CRS. Ground truth is **pyproj** (the C PROJ
library) transforming EPSG:4326 <-> EPSG:28992, so the fixture pins proj4rs's
``sterea`` + Bessel + 7-parameter ``towgs84`` transform against the reference
PROJ implementation. PROJ may apply the higher-accuracy RDNAPTRANS grid where
available; proj4rs uses the 7-parameter Helmert (~0.5 m), so the fixture
tolerance is set to 1.0 m (see ``TOL_M``).

Regeneration is operator-driven (``python gen_rd.py``); the TOML is committed
and **Python/pyproj are NOT build or test dependencies** — the Rust test reads
the committed data only.

Provenance: the fixture header records a sha256 of this generator so a fixture
can be traced to the exact oracle that produced it.
"""

from __future__ import annotations

import hashlib
from pathlib import Path

from pyproj import Transformer

# Netherlands landmarks spread across the RD New domain (corners + centre). The
# Amersfoort datum point (Onze Lieve Vrouwetoren) MUST be present — it is the RD
# false origin, RD ~ (155000, 463000). (name, lon_deg, lat_deg).
LANDMARKS = [
    ("Onze Lieve Vrouwetoren, Amersfoort", 5.387203, 52.155172),
    ("Dam Square, Amsterdam", 4.8936, 52.3731),
    ("Rotterdam Centraal", 4.4692, 51.9244),
    ("Groningen (north-east)", 6.5665, 53.2194),
    ("Maastricht (south-east)", 5.6889, 50.8514),
    ("Vlissingen (south-west)", 3.5736, 51.4426),
    ("Enschede (east)", 6.8937, 52.2215),
    ("Leeuwarden (north)", 5.7975, 53.2012),
]

# proj4rs uses the 7-parameter towgs84 Helmert; PROJ/pyproj may use the
# RDNAPTRANS grid. The two agree to ~0.5 m — pin at 1.0 m (research §Validation).
TOL_M = 1.0

# The authoritative CRS codes (PROJ resolves the best available transformation).
WGS84 = "EPSG:4326"
RD_NEW = "EPSG:28992"


def _fmt(x: float) -> str:
    return repr(float(x))


def main() -> None:
    here = Path(__file__).resolve().parent
    root = here.parents[1]
    out = root / "crates/envi-geo/tests/fixtures/oracle/rd_landmarks.toml"
    out.parent.mkdir(parents=True, exist_ok=True)

    sha = hashlib.sha256(Path(__file__).read_bytes()).hexdigest()[:16]

    # always_xy=True => (lon, lat) in / (x, y) out, matching envi-geo's ordering.
    fwd = Transformer.from_crs(WGS84, RD_NEW, always_xy=True)

    lines: list[str] = []
    lines.append("# generated by tools/crs_oracle/gen_rd.py — DO NOT EDIT")
    lines.append("# Cross-implementation CRS oracle: pyproj (C PROJ) vs proj4rs (pure Rust).")
    lines.append("# GEOX-04 / DATA-01: RD New (EPSG:28992) reprojection pinned to PROJ ground truth.")
    lines.append("")
    lines.append("[meta]")
    lines.append('oracle = "pyproj / C PROJ — EPSG:4326 <-> EPSG:28992"')
    lines.append(f'provenance = "gen_rd.py sha256:{sha}"')
    lines.append(f"tol_m = {_fmt(TOL_M)}")
    lines.append("")

    for name, lon, lat in LANDMARKS:
        x, y = fwd.transform(lon, lat)
        lines.append("[[case]]")
        lines.append(f'name = "{name}"')
        lines.append(f"lon_deg = {_fmt(lon)}")
        lines.append(f"lat_deg = {_fmt(lat)}")
        lines.append(f"rd_x_m = {_fmt(x)}")
        lines.append(f"rd_y_m = {_fmt(y)}")
        lines.append("")

    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {out} ({len(LANDMARKS)} cases, sha256:{sha})")


if __name__ == "__main__":
    main()
