//! Cross-implementation oracle test for the flat-terrain ground effect
//! (02-RESEARCH Pattern 4).
//!
//! Loads the committed `flat_sigma200.toml` (uniform σ=200, Sub-model 1) and
//! `flat_mixed_case21.toml` (FORCE case-21 mixed road/grass, Sub-model 2) —
//! generated by `tools/nord2000_oracle/gen_flat_fixtures.py` from
//! `scipy.special.wofz` — and asserts the engine's ΔL_t matches every 1/12-octave
//! point within the fixture tolerance (0.1 dB). Python/scipy are NOT needed at
//! test time; the TOML is the committed data. A transcription error in the
//! Sub-model 1/2 composition shows up here as a per-band mismatch.

use envi_engine::freq::FreqAxis;
use envi_engine::propagation::coherence::CoherenceInputs;
use envi_engine::propagation::rays::straight_rays;
use envi_engine::propagation::sound_speed_ms;
use envi_engine::propagation::terrain_effect::submodel1::{SubModel1Inputs, submodel1};
use envi_engine::propagation::terrain_effect::submodel2::{FlatGeometry, SurfaceStrip, submodel2};
use serde::Deserialize;

#[derive(Deserialize)]
struct Fixture {
    tolerance_db: f64,
    c0_m_s: f64,
    h_s: f64,
    h_r: f64,
    d: f64,
    bands: Vec<f64>,
}

fn load(name: &str) -> Fixture {
    let path = format!(
        "{}/tests/fixtures/oracle/{name}",
        env!("CARGO_MANIFEST_DIR")
    );
    let text = std::fs::read_to_string(&path).expect("oracle fixture TOML must exist");
    toml::from_str(&text).expect("oracle fixture TOML must parse")
}

fn coherence(c0: f64, d: f64, cv2: f64, ct2: f64) -> CoherenceInputs {
    CoherenceInputs {
        cv2,
        ct2,
        t_air_c: 15.0,
        c0,
        roughness_r: 0.0,
        f_delta_nu: 1.0,
        d_m: d,
    }
}

#[test]
fn engine_submodel1_matches_flat_sigma200_oracle() {
    let fx = load("flat_sigma200.toml");
    assert_eq!(fx.bands.len(), 105, "fixture must carry 105 points");
    let axis = FreqAxis::new();
    let rays = straight_rays(fx.d, fx.h_s, fx.h_r, fx.c0_m_s).unwrap();
    let coh = coherence(fx.c0_m_s, fx.d, 0.0, 0.0);
    for (i, &f) in axis.centres.iter().enumerate() {
        let inp = SubModel1Inputs {
            rays: &rays,
            sigma_kpa: 200.0,
            roughness_r: 0.0,
            coh: &coh,
        };
        let got = submodel1(f, &inp).unwrap().delta_l_db;
        let want = fx.bands[i];
        assert!(
            (got - want).abs() <= fx.tolerance_db,
            "σ=200 band {i} ({f:.2} Hz): engine {got:.4} vs oracle {want:.4} (±{})",
            fx.tolerance_db
        );
    }
    // c₀ consistency: the fixture c₀ is Eq. 335 at 15 °C.
    assert!((fx.c0_m_s - sound_speed_ms(15.0)).abs() < 1e-9);
}

#[test]
fn engine_submodel2_matches_flat_mixed_case21_oracle() {
    let fx = load("flat_mixed_case21.toml");
    assert_eq!(fx.bands.len(), 105, "fixture must carry 105 points");
    let axis = FreqAxis::new();
    let geom = FlatGeometry {
        d: fx.d,
        h_s: fx.h_s,
        h_r: fx.h_r,
        c0: fx.c0_m_s,
    };
    // FORCE case-21 mixed layout with forced turbulence (Cv²=0.12, CT²=0.008).
    let g = |x0, x1| SurfaceStrip {
        x_start: x0,
        x_end: x1,
        sigma_kpa: 20000.0,
        roughness_r: 0.0,
    };
    let d = |x0, x1| SurfaceStrip {
        x_start: x0,
        x_end: x1,
        sigma_kpa: 200.0,
        roughness_r: 0.0,
    };
    let strips = [g(0.0, 10.0), d(10.0, 50.0), g(50.0, 60.0), d(60.0, 97.5)];
    let coh = coherence(fx.c0_m_s, fx.d, 0.12, 0.008);
    for (i, &f) in axis.centres.iter().enumerate() {
        let got = submodel2(f, &strips, &geom, &coh).unwrap().delta_l_db;
        let want = fx.bands[i];
        assert!(
            (got - want).abs() <= fx.tolerance_db,
            "case-21 band {i} ({f:.2} Hz): engine {got:.4} vs oracle {want:.4} (±{})",
            fx.tolerance_db
        );
    }
}
