//! Cross-implementation minimum-phase transmission oracle test (T5).
//!
//! Loads the committed `tests/fixtures/oracle/minphase.toml` — generated by
//! `tools/nord2000_oracle/gen_minphase_fixtures.py` from the numpy.fft
//! even-mirror real-cepstrum recipe (05-RESEARCH Finding 3a/3e) — and asserts
//! the engine's `min_phase_phi_envi` reproduces every fixture band by **band
//! index** (never nominal Hz), plus the assembled native `TransmissionFilter`.
//! Python is NOT needed at test time.
//!
//! Oracle-independence caveat (D-09): the oracle implements the SAME mirror/fold
//! recipe as the engine, so it cross-checks the implementation (DFT conventions,
//! fold indices, sign), NOT the choice of recipe — the recipe itself is pinned
//! independently by 05-RESEARCH 3a/3b (a known min-phase system reproduced to
//! 6.7e-16) and the engine's T3 causality property test.
//!
//! Coverage assertions prevent a truncated / structureless fixture from passing
//! silently: exactly four cases, the flat case in the zero-phase regime, and at
//! least one case in the live-phase regime.

use envi_engine::freq::N_BANDS;
use envi_engine::propagation::transmission::{
    IsolationSpectrum, TransmissionFilter, min_phase_phi_envi,
};
use serde::Deserialize;

#[derive(Deserialize)]
struct Fixtures {
    meta: Meta,
    case: Vec<Case>,
}

#[derive(Deserialize)]
struct Meta {
    tol_abs_rad: f64,
}

#[derive(Deserialize)]
struct Case {
    name: String,
    r_db: Vec<f64>,
    phi_envi_rad: Vec<f64>,
}

fn load() -> Fixtures {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/fixtures/oracle/minphase.toml"
    );
    let text = std::fs::read_to_string(path).expect("minphase oracle TOML must exist");
    toml::from_str(&text).expect("minphase oracle TOML must parse")
}

#[test]
fn engine_min_phase_matches_oracle_grid() {
    let fx = load();
    let tol = fx.meta.tol_abs_rad;

    // Coverage: exactly four cases (flat + three live spectra).
    assert_eq!(fx.case.len(), 4, "oracle must carry exactly 4 R sets");

    let mut saw_zero_regime = false; // a flat R ⇒ φ ≡ 0
    let mut saw_live_regime = false; // a non-flat R ⇒ live phase

    for case in &fx.case {
        assert_eq!(
            case.r_db.len(),
            N_BANDS,
            "{}: r_db must have 105 values",
            case.name
        );
        assert_eq!(
            case.phi_envi_rad.len(),
            N_BANDS,
            "{}: phi_envi_rad must have 105 values",
            case.name
        );

        let r: [f64; N_BANDS] = case.r_db.clone().try_into().expect("105 R values per case");

        // (T5) φ per band index within tolerance of the committed oracle.
        let phi = min_phase_phi_envi(&r);
        let mut max_abs_phi = 0.0_f64;
        for (band, (&got, &want)) in phi.iter().zip(case.phi_envi_rad.iter()).enumerate() {
            assert!(
                (got - want).abs() <= tol,
                "{} band {band}: engine φ {got} vs oracle {want} (tol {tol})",
                case.name
            );
            max_abs_phi = max_abs_phi.max(got.abs());
        }

        // Native-filter cross-check: T_native = 10^(−R/20)·(cos φ, −sin φ) with
        // the ORACLE's φ (pins the explicit native negation end-to-end).
        let filter = TransmissionFilter::from_isolation(
            &IsolationSpectrum::new(r).unwrap_or_else(|e| panic!("{}: {e}", case.name)),
        );
        for (band, slot) in filter.bands.iter().enumerate() {
            let mag = 10f64.powf(-r[band] / 20.0);
            let want_re = mag * case.phi_envi_rad[band].cos();
            let want_im = mag * (-case.phi_envi_rad[band].sin());
            assert!(
                (slot.re - want_re).abs() <= 1e-9 && (slot.im - want_im).abs() <= 1e-9,
                "{} band {band}: native T {slot} vs |T|·(cosφ,−sinφ) ({want_re}, {want_im})",
                case.name
            );
        }

        if max_abs_phi < 1e-12 {
            saw_zero_regime = true;
        }
        if max_abs_phi > 0.01 {
            saw_live_regime = true;
        }
    }

    assert!(
        saw_zero_regime,
        "oracle must exercise the flat zero-phase regime (max|φ| < 1e-12)"
    );
    assert!(
        saw_live_regime,
        "oracle must exercise the live-phase regime (max|φ| > 0.01 rad)"
    );
}
