//! Cross-implementation oracle test (02-RESEARCH Pattern 4).
//!
//! Loads the committed `tests/fixtures/oracle/ground_w_qhat.toml` — generated by
//! `tools/nord2000_oracle/gen_ground_fixtures.py` from `scipy.special.wofz` — and
//! asserts the engine's own three-branch `faddeeva_w` and the `Q̂` chain match
//! every fixture point. Python/scipy are NOT needed at test time; the TOML is the
//! committed data. A transcription error in the document's w(z) approximation or
//! the Q̂ chain shows up here as a fixture mismatch.

use envi_engine::propagation::ground::{ground_impedance, spherical_q};
use envi_engine::propagation::special::faddeeva_w;
use num_complex::Complex;
use serde::Deserialize;

#[derive(Deserialize)]
struct Fixtures {
    meta: Meta,
    w: Vec<WRow>,
    qhat: Vec<QRow>,
}

#[derive(Deserialize)]
struct Meta {
    w_tol_rel: f64,
    qhat_tol_rel: f64,
}

#[derive(Deserialize)]
struct WRow {
    re: f64,
    im: f64,
    w_re: f64,
    w_im: f64,
}

#[derive(Deserialize)]
struct QRow {
    sigma: f64,
    f: f64,
    psi_g: f64,
    tau2: f64,
    q_re: f64,
    q_im: f64,
}

fn load() -> Fixtures {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/fixtures/oracle/ground_w_qhat.toml"
    );
    let text = std::fs::read_to_string(path).expect("oracle fixture TOML must exist");
    toml::from_str(&text).expect("oracle fixture TOML must parse")
}

fn rel_err(got: Complex<f64>, want: Complex<f64>) -> f64 {
    (got - want).norm() / want.norm().max(1e-12)
}

#[test]
fn engine_faddeeva_matches_oracle_w_grid() {
    let fx = load();
    assert!(fx.w.len() >= 30, "w grid must have ≥ 30 points");
    // All four quadrants must be represented (soft/hard ground reach each).
    let (mut q1, mut q2, mut q3, mut q4) = (false, false, false, false);
    for row in &fx.w {
        match (row.re >= 0.0, row.im >= 0.0) {
            (true, true) => q1 = true,
            (false, true) => q2 = true,
            (false, false) => q3 = true,
            (true, false) => q4 = true,
        }
        let got = faddeeva_w(Complex::new(row.re, row.im));
        let want = Complex::new(row.w_re, row.w_im);
        let err = rel_err(got, want);
        assert!(
            err <= fx.meta.w_tol_rel,
            "w({}+{}j): rel err {:.2e} > {:.1e}",
            row.re,
            row.im,
            err,
            fx.meta.w_tol_rel
        );
    }
    assert!(q1 && q2 && q3 && q4, "all four quadrants must be covered");
}

#[test]
fn engine_spherical_q_matches_oracle_qhat_grid() {
    let fx = load();
    assert!(fx.qhat.len() >= 20, "Q̂ grid must have ≥ 20 points");
    for row in &fx.qhat {
        let z_g = ground_impedance(row.f, row.sigma).expect("valid σ");
        let got = spherical_q(row.f, row.tau2, row.psi_g, z_g);
        let want = Complex::new(row.q_re, row.q_im);
        let err = rel_err(got, want);
        assert!(
            err <= fx.meta.qhat_tol_rel,
            "Q̂(σ={}, f={}): rel err {:.2e} > {:.1e}",
            row.sigma,
            row.f,
            err,
            fx.meta.qhat_tol_rel
        );
    }
}
