//! Cross-implementation Sub-model 11 (reflection effect) oracle test.
//!
//! Loads the committed `tests/fixtures/oracle/submodel11.toml` — generated by
//! `tools/nord2000_oracle/gen_submodel11_fixtures.py` from an independent
//! transcription of AV 1106/07 §5.20 (Eq. 296 `L11` + Eq. 339 `CalcFZd`) — and
//! asserts the engine's `submodel11` reproduces every fixture row by **band
//! index** (never nominal Hz). Python is NOT needed at test time.
//!
//! A coverage assertion prevents a truncated / structureless fixture from
//! passing silently. Per the standing oracle-independence caveat the oracle
//! cross-checks the implementation, not the spec reading; there is no FORCE
//! numeric gate on SM11 (the city cases stay `Skipped` on the [ASSUMED]
//! emission coefficients).

use envi_engine::freq::FreqAxis;
use envi_engine::propagation::terrain_effect::submodel11::{ReflectionConfig, submodel11};
use serde::Deserialize;

#[derive(Deserialize)]
struct Fixtures {
    meta: Meta,
    case: Vec<Case>,
}

#[derive(Deserialize)]
struct Meta {
    tol_abs_db: f64,
    c0: f64,
}

#[derive(Deserialize)]
struct Case {
    name: String,
    r_s: f64,
    r_r: f64,
    alpha: f64,
    half_up: f64,
    half_down: f64,
    half_left: f64,
    half_right: f64,
    band_index: Vec<usize>,
    l11_db: Vec<f64>,
}

fn load() -> Fixtures {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/fixtures/oracle/submodel11.toml"
    );
    let text = std::fs::read_to_string(path).expect("submodel11 oracle TOML must exist");
    toml::from_str(&text).expect("submodel11 oracle TOML must parse")
}

#[test]
fn engine_submodel11_matches_oracle_grid() {
    let fx = load();
    let axis = FreqAxis::new();
    assert!(
        fx.case.len() >= 3,
        "oracle must carry ≥ 3 reflection configs"
    );

    let mut total_rows = 0usize;
    let mut saw_zero = false; // a large / low-freq reflector ⇒ L11 ≈ 0
    let mut saw_attenuated = false; // absorption or a sub-Fresnel reflector

    for case in &fx.case {
        let cfg = ReflectionConfig {
            r_s: case.r_s,
            r_r: case.r_r,
            alpha: case.alpha,
            c0: fx.meta.c0,
            half_up: case.half_up,
            half_down: case.half_down,
            half_left: case.half_left,
            half_right: case.half_right,
        };
        assert_eq!(
            case.band_index.len(),
            case.l11_db.len(),
            "{}: parallel fixture arrays must match",
            case.name
        );
        for (k, &bi) in case.band_index.iter().enumerate() {
            let f = axis.centres[bi];
            let got = submodel11(f, &cfg)
                .unwrap_or_else(|e| panic!("{} band {bi}: submodel11 failed: {e}", case.name));
            let want = case.l11_db[k];
            assert!(
                (got - want).abs() <= fx.meta.tol_abs_db,
                "{} band {bi} ({f:.2} Hz): L11 {got} vs oracle {want} (tol {})",
                case.name,
                fx.meta.tol_abs_db
            );
            if want.abs() < 1e-6 {
                saw_zero = true;
            }
            if want < -0.5 {
                saw_attenuated = true;
            }
            total_rows += 1;
        }
    }

    assert!(
        total_rows >= 30,
        "oracle grid too small ({total_rows} rows)"
    );
    assert!(
        saw_zero && saw_attenuated,
        "oracle must exercise both full-efficiency and attenuated reflections"
    );
}
