//! Cross-implementation Sub-model 3 (non-flat terrain) oracle test.
//!
//! Loads the committed `tests/fixtures/oracle/submodel3.toml` — generated by
//! `tools/nord2000_oracle/gen_submodel3_fixtures.py` from an independent
//! transcription of AV 1106/07 §5.12 (Eqs. 134-140, 156) over the concave path —
//! and asserts the engine's `SubModel3::eval` reproduces every fixture row by
//! **band index** (never nominal Hz). Python is NOT needed at test time.
//!
//! Scope: concave segments over horizontal ground (the reflection reduces to the
//! flat two-ray model with segment-relative heights). A coverage assertion
//! prevents a truncated fixture from passing silently. The convex/wedge path is
//! a typed engine error and is not fixtured.

use envi_engine::freq::FreqAxis;
use envi_engine::propagation::coherence::CoherenceInputs;
use envi_engine::propagation::sound_speed_ms;
use envi_engine::propagation::terrain_effect::submodel3::{Segment3, SubModel3};
use serde::Deserialize;

#[derive(Deserialize)]
struct Fixtures {
    meta: Meta,
    case: Vec<Case>,
}

#[derive(Deserialize)]
struct Meta {
    tol_abs_db: f64,
}

#[derive(Deserialize)]
struct Case {
    name: String,
    source: [f64; 2],
    receiver: [f64; 2],
    seg_a: Vec<[f64; 2]>,
    seg_b: Vec<[f64; 2]>,
    sigma: Vec<f64>,
    rough: Vec<f64>,
    band_index: Vec<usize>,
    delta_l_db: Vec<f64>,
}

fn load() -> Fixtures {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/fixtures/oracle/submodel3.toml"
    );
    let text = std::fs::read_to_string(path).expect("submodel3 oracle TOML must exist");
    toml::from_str(&text).expect("submodel3 oracle TOML must parse")
}

#[test]
fn engine_submodel3_matches_oracle_grid() {
    let fx = load();
    let axis = FreqAxis::new();
    let c0 = sound_speed_ms(15.0);
    assert!(fx.case.len() >= 2, "oracle must carry ≥ 2 concave configs");

    let mut total_rows = 0usize;
    let mut saw_negative = false; // an interference dip (ΔL < 0)
    let mut saw_positive = false; // constructive band (ΔL > 0)

    for case in &fx.case {
        let coh = CoherenceInputs {
            cv2: 0.0,
            ct2: 0.0,
            t_air_c: 15.0,
            c0,
            roughness_r: 0.0,
            f_delta_nu: 1.0,
            d_m: (case.receiver[0] - case.source[0]).abs().max(1e-6),
        };
        let segments: Vec<Segment3> = (0..case.seg_a.len())
            .map(|i| Segment3 {
                seg_a: case.seg_a[i],
                seg_b: case.seg_b[i],
                sigma_kpa: case.sigma[i],
                roughness_r: case.rough[i],
            })
            .collect();
        let sm3 = SubModel3::new(case.source, case.receiver, c0, segments, None)
            .unwrap_or_else(|e| panic!("{}: SubModel3 build failed: {e}", case.name));

        assert_eq!(
            case.band_index.len(),
            case.delta_l_db.len(),
            "{}: parallel fixture arrays must match",
            case.name
        );
        for (k, &bi) in case.band_index.iter().enumerate() {
            let f = axis.centres[bi];
            let got = sm3
                .eval(f, &coh)
                .unwrap_or_else(|e| panic!("{} band {bi}: eval failed: {e}", case.name));
            let want = case.delta_l_db[k];
            assert!(
                (got.delta_l_db - want).abs() <= fx.meta.tol_abs_db,
                "{} band {bi} ({f:.2} Hz): ΔL₃ {} vs oracle {want} (tol {})",
                case.name,
                got.delta_l_db,
                fx.meta.tol_abs_db
            );
            if want < -0.5 {
                saw_negative = true;
            }
            if want > 0.5 {
                saw_positive = true;
            }
            total_rows += 1;
        }
    }

    // Coverage: a truncated fixture (or one that lost its interference structure)
    // must not pass silently.
    assert!(
        total_rows >= 20,
        "oracle grid too small ({total_rows} rows)"
    );
    assert!(
        saw_negative && saw_positive,
        "oracle must exercise both interference dips and constructive bands"
    );
}
