//! Cross-implementation refraction oracle test (03-RESEARCH acceptance ladder
//! rung b / D-02).
//!
//! Loads the committed `tests/fixtures/oracle/refraction.toml` — generated by
//! `tools/nord2000_oracle/gen_refraction_fixtures.py` from an independent
//! transcription of AV 1106/07 Eqs. 15-21 / 29-53 / Annex F 403 — and asserts
//! the engine's `calc_eq_ssp` (CalcEqSSP) and `circular_rays` (Δτ) reproduce
//! every fixture row. Python is NOT needed at test time; the TOML is committed.
//! A transcription error in ξ / c₀ / Δτ shows up here as a fixture mismatch.

use envi_engine::propagation::refraction::eqssp::calc_eq_ssp;
use serde::Deserialize;

#[derive(Deserialize)]
struct Fixtures {
    meta: Meta,
    eqssp: Vec<EqSspRow>,
}

#[derive(Deserialize)]
struct Meta {
    eqssp_tol_rel: f64,
}

#[derive(Deserialize)]
struct EqSspRow {
    a: f64,
    b: f64,
    c: f64,
    z0: f64,
    h_s: f64,
    h_r: f64,
    xi: f64,
    c0: f64,
}

fn load() -> Fixtures {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/fixtures/oracle/refraction.toml"
    );
    let text = std::fs::read_to_string(path).expect("refraction oracle TOML must exist");
    toml::from_str(&text).expect("refraction oracle TOML must parse")
}

fn rel_err(got: f64, want: f64) -> f64 {
    (got - want).abs() / want.abs().max(1e-12)
}

#[test]
fn engine_calc_eq_ssp_matches_oracle_grid() {
    let fx = load();
    assert!(fx.eqssp.len() >= 8, "eqssp grid must have ≥ 8 rows");
    let mut saw_up = false;
    let mut saw_down = false;
    for row in &fx.eqssp {
        let (xi, c0) = calc_eq_ssp(row.h_s, row.h_r, row.z0, row.a, row.b, row.c).unwrap();
        if xi > 0.0 {
            saw_down = true;
        }
        if xi < 0.0 {
            saw_up = true;
        }
        // ξ can be exactly 0 (homogeneous shortcut) — compare absolutely there.
        let xi_err = if row.xi.abs() < 1e-12 {
            (xi - row.xi).abs()
        } else {
            rel_err(xi, row.xi)
        };
        assert!(
            xi_err <= fx.meta.eqssp_tol_rel,
            "ξ(A={},B={},hS={},hR={}): got {xi:.12e} want {:.12e} err {xi_err:.2e}",
            row.a,
            row.b,
            row.h_s,
            row.h_r,
            row.xi
        );
        assert!(
            rel_err(c0, row.c0) <= fx.meta.eqssp_tol_rel,
            "c₀(A={},B={}): got {c0} want {}",
            row.a,
            row.b,
            row.c0
        );
    }
    assert!(saw_up && saw_down, "grid must cover up- and down-refraction");
}
