//! Cross-implementation forest (Sub-model 10) excess-attenuation oracle test.
//!
//! Loads the committed `tests/fixtures/oracle/forest.toml` — generated by
//! `tools/nord2000_oracle/gen_forest_fixtures.py` from an independent
//! transcription of AV 1106/07 §5.19 (Eqs. 288-291 + Tables 8/9, with
//! `scipy.interpolate.PchipInterpolator` for the Table-9 lookup) — and asserts
//! the engine's `forest_delta_l` reproduces every fixture row by **band index**
//! (never nominal Hz). Python is NOT needed at test time.
//!
//! Standing oracle-independence caveat (05-RESEARCH): the oracle shares the
//! engine's equation transcription and interpolation scheme (nesting order,
//! clamps, FC-Butland PCHIP), so it cross-checks the IMPLEMENTATION, not the
//! spec reading — the node-exact analytic anchors (F1/F2 in `forest.rs`) pin the
//! spec reading independently. Coverage assertions prevent a truncated fixture
//! from passing silently.

use envi_engine::forest::{ForestCrossing, forest_delta_l};
use envi_engine::freq::FreqAxis;
use serde::Deserialize;

#[derive(Deserialize)]
struct Fixtures {
    meta: Meta,
    case: Vec<Case>,
}

#[derive(Deserialize)]
struct Meta {
    tol_abs_db: f64,
    c0: f64,
}

#[derive(Deserialize)]
struct Case {
    name: String,
    d_m: f64,
    density: f64,
    stem_radius: f64,
    absorption: f64,
    height: f64,
    band_index: Vec<usize>,
    delta_l_db: Vec<f64>,
}

fn load() -> Fixtures {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/fixtures/oracle/forest.toml"
    );
    let text = std::fs::read_to_string(path).expect("forest oracle TOML must exist");
    toml::from_str(&text).expect("forest oracle TOML must parse")
}

#[test]
fn engine_forest_delta_l_matches_oracle_grid() {
    let fx = load();
    let axis = FreqAxis::new();
    assert!(fx.case.len() >= 4, "oracle must carry ≥ 4 forest configs");

    let mut total_rows = 0usize;
    let mut saw_zero = false; // an all-zero (d_m = 0 / low-freq) row
    let mut saw_attenuated = false; // a genuinely attenuating row
    let mut saw_floor = false; // at least one −15.0 dB floor value

    for case in &fx.case {
        let fc = ForestCrossing::new(
            case.d_m,
            case.density,
            case.stem_radius,
            case.absorption,
            case.height,
        )
        .unwrap_or_else(|e| panic!("{}: ForestCrossing::new failed: {e}", case.name));
        assert_eq!(
            case.band_index.len(),
            case.delta_l_db.len(),
            "{}: parallel fixture arrays must match",
            case.name
        );
        for (k, &bi) in case.band_index.iter().enumerate() {
            let f = axis.centres[bi];
            let got = forest_delta_l(f, &fc, fx.meta.c0);
            let want = case.delta_l_db[k];
            assert!(
                (got - want).abs() <= fx.meta.tol_abs_db,
                "{} band {bi} ({f:.2} Hz): ΔL_s {got} vs oracle {want} (tol {})",
                case.name,
                fx.meta.tol_abs_db
            );
            if want.abs() < 1e-9 {
                saw_zero = true;
            }
            if want < -0.5 {
                saw_attenuated = true;
            }
            if (want - (-15.0)).abs() < 1e-9 {
                saw_floor = true;
            }
            total_rows += 1;
        }
    }

    assert!(
        total_rows >= 40,
        "oracle grid too small ({total_rows} rows)"
    );
    assert!(
        saw_zero && saw_attenuated && saw_floor,
        "oracle must exercise the zero, attenuating, and −15 dB floor regimes \
         (zero={saw_zero}, attenuated={saw_attenuated}, floor={saw_floor})"
    );
}
