//! Cross-implementation wedge-diffraction oracle test (02-RESEARCH Pattern 4).
//!
//! Loads the committed `tests/fixtures/oracle/wedge_il.toml` — generated by
//! `tools/nord2000_oracle/gen_wedge_fixtures.py`, an independent Hadden–Pierce
//! implementation whose wedge-face `Q̂` comes from `scipy.special.wofz` — and
//! asserts the engine's `pwedge`/`p2wedge`/`p2edge` match every fixture row. A
//! transcription error in the engine's four-term sum, its own `w(z)`, or a
//! composite argument list shows up here as a fixture mismatch. Python/scipy are
//! NOT needed at test time; the TOML is the committed data.

use envi_engine::propagation::diffraction::{
    TwoWedgeGeometry, TwoWedgeImpedances, WedgeGeometry, WedgePrimary, p2edge, p2wedge, pwedge,
};
use envi_engine::propagation::sound_speed_ms;
use num_complex::Complex;
use serde::Deserialize;

const HARD: Complex<f64> = Complex::new(1.0e9, 0.0);

#[derive(Deserialize)]
struct Fixtures {
    meta: Meta,
    il_hard: Vec<IlRow>,
    shadow: Vec<ShadowRow>,
    soft_face: Vec<SoftRow>,
    p2edge: Vec<TwoRow>,
    p2wedge: Vec<TwoRow>,
}

#[derive(Deserialize)]
struct Meta {
    il_tol_db: f64,
    q_tol_rel: f64,
    shadow_tol: f64,
}

#[derive(Deserialize)]
struct IlRow {
    f: f64,
    il_db: f64,
    p_re: f64,
    p_im: f64,
}

#[derive(Deserialize)]
struct ShadowRow {
    theta_s: f64,
    theta_r: f64,
    beta: f64,
    tau_s: f64,
    tau_r: f64,
    r_s: f64,
    r_r: f64,
    mag_ell: f64,
}

#[derive(Deserialize)]
struct SoftRow {
    f: f64,
    z_re: f64,
    z_im: f64,
    theta_s: f64,
    theta_r: f64,
    beta: f64,
    tau_s: f64,
    tau_r: f64,
    r_s: f64,
    r_r: f64,
    p_re: f64,
    p_im: f64,
}

#[derive(Deserialize)]
struct TwoRow {
    f: f64,
    beta1: f64,
    theta_1s: f64,
    theta_1r: f64,
    beta2: f64,
    theta_2s: f64,
    theta_2r: f64,
    tau_s: f64,
    tau_m: f64,
    tau_r: f64,
    r_s: f64,
    r_m: f64,
    r_r: f64,
    p_re: f64,
    p_im: f64,
}

fn load() -> Fixtures {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/fixtures/oracle/wedge_il.toml"
    );
    let text = std::fs::read_to_string(path).expect("wedge oracle fixture TOML must exist");
    toml::from_str(&text).expect("wedge oracle fixture TOML must parse")
}

fn wedge(
    row_theta_s: f64,
    row_theta_r: f64,
    beta: f64,
    tau_s: f64,
    tau_r: f64,
    r_s: f64,
    r_r: f64,
) -> WedgeGeometry {
    WedgeGeometry {
        tau_s,
        tau_r,
        tau: tau_s + tau_r,
        r_s,
        r_r,
        l: r_s + r_r,
        theta_s: row_theta_s,
        theta_r: row_theta_r,
        beta,
    }
}

fn two_wedge(r: &TwoRow) -> TwoWedgeGeometry {
    TwoWedgeGeometry {
        beta1: r.beta1,
        theta_1s: r.theta_1s,
        theta_1r: r.theta_1r,
        beta2: r.beta2,
        theta_2s: r.theta_2s,
        theta_2r: r.theta_2r,
        tau_s: r.tau_s,
        tau_m: r.tau_m,
        tau_r: r.tau_r,
        r_s: r.r_s,
        r_m: r.r_m,
        r_r: r.r_r,
    }
}

/// Rebuild the hard thin-screen anchor geometry (S=(0,1) T=(50,6) R=(100,1)).
fn hard_anchor(f: f64) -> (WedgeGeometry, f64) {
    let c0 = sound_speed_ms(15.0);
    let (s, t, r) = (
        (0.0_f64, 1.0_f64),
        (50.0_f64, 6.0_f64),
        (100.0_f64, 1.0_f64),
    );
    let r_s = (t.0 - s.0).hypot(t.1 - s.1);
    let r_r = (r.0 - t.0).hypot(r.1 - t.1);
    let face = -std::f64::consts::FRAC_PI_2;
    let ang =
        |p: (f64, f64)| ((p.1 - t.1).atan2(p.0 - t.0) - face).rem_euclid(std::f64::consts::TAU);
    let _ = f;
    (
        WedgeGeometry {
            tau_s: r_s / c0,
            tau_r: r_r / c0,
            tau: (r_s + r_r) / c0,
            r_s,
            r_r,
            l: r_s + r_r,
            theta_s: ang(s),
            theta_r: ang(r),
            beta: std::f64::consts::TAU * 0.9999,
        },
        (r.0 - s.0).hypot(r.1 - s.1),
    )
}

#[test]
fn engine_pwedge_matches_oracle_hard_screen_il_grid() {
    let fx = load();
    assert!(fx.il_hard.len() >= 6);
    for row in &fx.il_hard {
        let (geo, r_sr) = hard_anchor(row.f);
        let p = pwedge(row.f, &geo, HARD, HARD).unwrap();
        let il = -20.0 * (p.norm() * r_sr).log10();
        assert!(
            (il - row.il_db).abs() <= fx.meta.il_tol_db,
            "IL({} Hz): engine {:.4} vs oracle {:.4} dB",
            row.f,
            il,
            row.il_db
        );
        // Complex pressure itself (not just the level) must match.
        let want = Complex::new(row.p_re, row.p_im);
        assert!((p - want).norm() / want.norm() <= fx.meta.q_tol_rel);
    }
}

#[test]
fn engine_pwedge_matches_oracle_shadow_boundary_series() {
    let fx = load();
    for row in &fx.shadow {
        let geo = wedge(
            row.theta_s,
            row.theta_r,
            row.beta,
            row.tau_s,
            row.tau_r,
            row.r_s,
            row.r_r,
        );
        let p = pwedge(1000.0, &geo, HARD, HARD).unwrap();
        let mag = p.norm() * geo.l;
        assert!(
            (mag - row.mag_ell).abs() <= 1e-3,
            "shadow |p|·ℓ engine {:.5} vs oracle {:.5}",
            mag,
            row.mag_ell
        );
    }
    // The series must bracket the 0.500 half-field limit near the boundary.
    let near = fx
        .shadow
        .iter()
        .map(|r| (r.mag_ell - 0.5).abs())
        .fold(f64::INFINITY, f64::min);
    assert!(
        near <= fx.meta.shadow_tol,
        "no fixture row within {} of 0.5",
        fx.meta.shadow_tol
    );
}

#[test]
fn engine_pwedge_matches_oracle_finite_impedance_faces() {
    let fx = load();
    for row in &fx.soft_face {
        let z = Complex::new(row.z_re, row.z_im);
        let geo = wedge(
            row.theta_s,
            row.theta_r,
            row.beta,
            row.tau_s,
            row.tau_r,
            row.r_s,
            row.r_r,
        );
        let p = pwedge(row.f, &geo, z, z).unwrap();
        let want = Complex::new(row.p_re, row.p_im);
        assert!(
            (p - want).norm() / want.norm() <= fx.meta.q_tol_rel,
            "soft-face pwedge({} Hz): engine {} vs oracle {}",
            row.f,
            p,
            want
        );
        assert!(
            p.im.abs() > 1e-9,
            "finite-impedance wedge must stay complex"
        );
    }
}

#[test]
fn engine_p2edge_matches_oracle_thick_screen() {
    let fx = load();
    assert!(!fx.p2edge.is_empty());
    for row in &fx.p2edge {
        let g = two_wedge(row);
        let p = p2edge(row.f, &g, WedgePrimary::First, HARD, HARD).unwrap();
        let want = Complex::new(row.p_re, row.p_im);
        assert!(
            (p - want).norm() / want.norm() <= fx.meta.q_tol_rel,
            "p2edge({} Hz): engine {} vs oracle {}",
            row.f,
            p,
            want
        );
    }
}

#[test]
fn engine_p2wedge_matches_oracle_two_wedges() {
    let fx = load();
    assert!(!fx.p2wedge.is_empty());
    let z = TwoWedgeImpedances {
        z_1s: HARD,
        z_1r: HARD,
        z_2s: HARD,
        z_2r: HARD,
    };
    for row in &fx.p2wedge {
        let g = two_wedge(row);
        let p = p2wedge(row.f, &g, WedgePrimary::First, &z).unwrap();
        let want = Complex::new(row.p_re, row.p_im);
        assert!(
            (p - want).norm() / want.norm() <= fx.meta.q_tol_rel,
            "p2wedge({} Hz): engine {} vs oracle {}",
            row.f,
            p,
            want
        );
    }
}
