//! Cross-implementation refraction oracle test (03-RESEARCH acceptance ladder
//! rung b / D-02).
//!
//! Loads the committed `tests/fixtures/oracle/refraction.toml` — generated by
//! `tools/nord2000_oracle/gen_refraction_fixtures.py` from an independent
//! transcription of AV 1106/07 Eqs. 15-21 / 29-53 / Annex F 403 — and asserts
//! the engine's `calc_eq_ssp` (CalcEqSSP) and `circular_rays` (Δτ) reproduce
//! every fixture row. Python is NOT needed at test time; the TOML is committed.
//! A transcription error in ξ / c₀ / Δτ shows up here as a fixture mismatch.

use envi_engine::freq::FreqAxis;
use envi_engine::propagation::rays::circular_rays;
use envi_engine::propagation::refraction::eqssp::{calc_eq_ssp, calc_eq_ssp_ground};
use envi_harness::weather::route3::fit_profile;
use serde::Deserialize;

#[derive(Deserialize)]
struct Fixtures {
    meta: Meta,
    eqssp: Vec<EqSspRow>,
    eqssp_ground: Vec<EqSspGroundRow>,
    dtau: Vec<DtauRow>,
    route3_fit: Vec<Route3FitRow>,
}

#[derive(Deserialize)]
struct Meta {
    eqssp_tol_rel: f64,
    eqssp_ground_tol_rel: f64,
    dtau_tol_rel: f64,
    route3_fit_tol_abs: f64,
}

#[derive(Deserialize)]
struct Route3FitRow {
    z0: f64,
    heights: Vec<f64>,
    c_eff: Vec<f64>,
    a: f64,
    b: f64,
    c: f64,
}

#[derive(Deserialize)]
struct EqSspGroundRow {
    a: f64,
    b: f64,
    c: f64,
    z0: f64,
    h_s: f64,
    h_r: f64,
    d: f64,
    sigma_kpa: f64,
    band_index: usize,
    xi: f64,
    c0: f64,
}

#[derive(Deserialize)]
struct EqSspRow {
    a: f64,
    b: f64,
    c: f64,
    z0: f64,
    h_s: f64,
    h_r: f64,
    xi: f64,
    c0: f64,
}

#[derive(Deserialize)]
struct DtauRow {
    h_s: f64,
    h_r: f64,
    d: f64,
    xi: f64,
    c0: f64,
    dtau: f64,
}

fn load() -> Fixtures {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/fixtures/oracle/refraction.toml"
    );
    let text = std::fs::read_to_string(path).expect("refraction oracle TOML must exist");
    toml::from_str(&text).expect("refraction oracle TOML must parse")
}

fn rel_err(got: f64, want: f64) -> f64 {
    (got - want).abs() / want.abs().max(1e-12)
}

#[test]
fn engine_calc_eq_ssp_matches_oracle_grid() {
    let fx = load();
    assert!(fx.eqssp.len() >= 8, "eqssp grid must have ≥ 8 rows");
    let mut saw_up = false;
    let mut saw_down = false;
    for row in &fx.eqssp {
        let (xi, c0) = calc_eq_ssp(row.h_s, row.h_r, row.z0, row.a, row.b, row.c).unwrap();
        if xi > 0.0 {
            saw_down = true;
        }
        if xi < 0.0 {
            saw_up = true;
        }
        // ξ can be exactly 0 (homogeneous shortcut) — compare absolutely there.
        let xi_err = if row.xi.abs() < 1e-12 {
            (xi - row.xi).abs()
        } else {
            rel_err(xi, row.xi)
        };
        assert!(
            xi_err <= fx.meta.eqssp_tol_rel,
            "ξ(A={},B={},hS={},hR={}): got {xi:.12e} want {:.12e} err {xi_err:.2e}",
            row.a,
            row.b,
            row.h_s,
            row.h_r,
            row.xi
        );
        assert!(
            rel_err(c0, row.c0) <= fx.meta.eqssp_tol_rel,
            "c₀(A={},B={}): got {c0} want {}",
            row.a,
            row.b,
            row.c0
        );
    }
    assert!(
        saw_up && saw_down,
        "grid must cover up- and down-refraction"
    );
}

#[test]
fn engine_calc_eq_ssp_ground_matches_oracle_by_band_index() {
    let fx = load();
    assert!(
        fx.eqssp_ground.len() >= 16,
        "eqssp_ground grid must have ≥ 16 rows"
    );
    let axis = FreqAxis::new();
    let (mut saw_zero, mut saw_positive, mut saw_flat_hard) = (false, false, false);
    for row in &fx.eqssp_ground {
        // Compare by BAND INDEX (D-14): evaluate at the exact 1/12-oct centre.
        let f = axis.centres[row.band_index];
        let (xi, c0) = calc_eq_ssp_ground(
            f,
            row.d,
            row.h_s,
            row.h_r,
            row.sigma_kpa,
            row.z0,
            row.a,
            row.b,
            row.c,
        )
        .unwrap();
        if xi == 0.0 {
            saw_zero = true;
        }
        if xi.abs() > 0.0 {
            saw_positive = true;
        }
        if row.sigma_kpa >= 1.0e4 {
            saw_flat_hard = true;
        }
        // ξ can be exactly 0 below fL / homogeneous — compare absolutely there.
        let xi_err = if row.xi.abs() < 1e-12 {
            (xi - row.xi).abs()
        } else {
            rel_err(xi, row.xi)
        };
        assert!(
            xi_err <= fx.meta.eqssp_ground_tol_rel,
            "ξ(f)[band {}] (σ={},A={},B={}): got {xi:.12e} want {:.12e} err {xi_err:.2e}",
            row.band_index,
            row.sigma_kpa,
            row.a,
            row.b,
            row.xi
        );
        assert!(
            rel_err(c0, row.c0) <= fx.meta.eqssp_ground_tol_rel,
            "c₀(f)[band {}]: got {c0} want {}",
            row.band_index,
            row.c0
        );
    }
    assert!(
        saw_zero && saw_positive && saw_flat_hard,
        "grid must cover below-fL (ξ=0), interpolated (ξ≠0), and hard-ground rows"
    );
}

#[test]
fn engine_route3_fit_recovers_oracle_coefficients() {
    let fx = load();
    assert!(
        fx.route3_fit.len() >= 4,
        "route3_fit grid must have ≥ 4 rows"
    );
    let (mut saw_up, mut saw_down) = (false, false);
    for row in &fx.route3_fit {
        let (a, b, c) = fit_profile(&row.heights, &row.c_eff, row.z0).unwrap();
        if row.a > 0.0 {
            saw_down = true; // positive log slope ⇒ downward-refraction profile
        }
        if row.a < 0.0 {
            saw_up = true;
        }
        assert!(
            (a - row.a).abs() <= fx.meta.route3_fit_tol_abs,
            "A: got {a:.12} want {:.12}",
            row.a
        );
        assert!(
            (b - row.b).abs() <= fx.meta.route3_fit_tol_abs,
            "B: got {b:.12} want {:.12}",
            row.b
        );
        assert!(
            (c - row.c).abs() <= fx.meta.route3_fit_tol_abs,
            "C: got {c:.12} want {:.12}",
            row.c
        );
    }
    assert!(
        saw_up && saw_down,
        "route3_fit grid must cover up- and down-refraction profiles"
    );
}

#[test]
fn engine_circular_rays_dtau_matches_oracle_grid() {
    let fx = load();
    assert!(fx.dtau.len() >= 6, "Δτ grid must have ≥ 6 rows");
    for row in &fx.dtau {
        let pair = circular_rays(row.d, row.h_s, row.h_r, row.xi, row.c0).unwrap();
        // Δτ = 0 in a shadow zone — compare absolutely there.
        let err = if row.dtau.abs() < 1e-12 {
            (pair.dtau - row.dtau).abs()
        } else {
            rel_err(pair.dtau, row.dtau)
        };
        assert!(
            err <= fx.meta.dtau_tol_rel,
            "Δτ(ξ={},d={},hS={},hR={}): got {:.12e} want {:.12e} err {err:.2e}",
            row.xi,
            row.d,
            row.h_s,
            row.h_r,
            pair.dtau,
            row.dtau
        );
    }
}
