//! Cross-implementation screen-over-ground oracle test (02-RESEARCH Pattern 4).
//!
//! Loads the committed `tests/fixtures/oracle/screen_thin.toml` — generated by
//! `tools/nord2000_oracle/gen_screen_fixtures.py`, an independent Sub-model 4
//! (four-path image model) + Sub-model 7 (turbulence scattering) implementation
//! whose wedge-face `Q̂` comes from `scipy.special.wofz` — and asserts the
//! engine's `submodel4` + `submodel7_delta_l` reproduce the combined `ΔL₄+ΔL₇`
//! curve for the literal case-71 thin-screen geometry at all 105 grid points,
//! within 0.1 dB. A transcription error in the engine's Eq. 187/188 combination,
//! its Table 6/7, or its `w(z)` shows up here as a fixture mismatch. Python/scipy
//! are NOT needed at test time; the TOML is the committed data.

use envi_engine::propagation::coherence::CoherenceInputs;
use envi_engine::propagation::sound_speed_ms;
use envi_engine::propagation::terrain_effect::screen::{
    ScreenConfig, SurfaceStrip, submodel4, submodel4_c_sr,
};
use envi_engine::propagation::terrain_effect::submodel7::{
    ScreenScatterGeometry, combine_scatter, submodel7_delta_l,
};
use num_complex::Complex;
use serde::Deserialize;

const HARD: Complex<f64> = Complex::new(1.0e9, 0.0);

#[derive(Deserialize)]
struct Fixtures {
    meta: Meta,
    point: Vec<Point>,
}

#[derive(Deserialize)]
struct Meta {
    tol_db: f64,
    s_x: f64,
    s_z: f64,
    r_x: f64,
    r_z: f64,
    edge_x: f64,
    edge_z: f64,
    sigma_kpa: f64,
    cv2: f64,
    ct2: f64,
    t_air_c: f64,
    r1_sm7: f64,
    r2_sm7: f64,
    h_e: f64,
}

#[derive(Deserialize)]
struct Point {
    f: f64,
    delta_l: f64,
}

fn load() -> Fixtures {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/fixtures/oracle/screen_thin.toml"
    );
    let text = std::fs::read_to_string(path).expect("screen oracle fixture TOML must exist");
    toml::from_str(&text).expect("screen oracle fixture TOML must parse")
}

#[test]
fn engine_screen_sm4_plus_sm7_matches_oracle_thin_curve() {
    let fx = load();
    let m = &fx.meta;
    assert_eq!(fx.point.len(), 105, "expected the full 105-point grid");

    let c0 = sound_speed_ms(m.t_air_c);
    let coh = CoherenceInputs {
        cv2: m.cv2,
        ct2: m.ct2,
        t_air_c: m.t_air_c,
        c0,
        roughness_r: 0.0,
        f_delta_nu: 1.0,
        d_m: m.r_x - m.s_x,
    };
    // Screen shape [W₁, T, W₂] — thin spike at edge_x.
    let screen = [
        [m.edge_x - 0.01, 0.0],
        [m.edge_x, m.edge_z],
        [m.edge_x + 0.01, 0.0],
    ];
    // Wide flat reflecting strips (Fresnel weight saturates to 1 ⇒ w_Q = 1).
    let before = [SurfaceStrip {
        seg_a: [-500.0, 0.0],
        seg_b: [m.edge_x, 0.0],
        sigma_kpa: m.sigma_kpa,
        roughness_r: 0.0,
    }];
    let after = [SurfaceStrip {
        seg_a: [m.edge_x, 0.0],
        seg_b: [500.0, 0.0],
        sigma_kpa: m.sigma_kpa,
        roughness_r: 0.0,
    }];
    let cfg = ScreenConfig {
        source: [m.s_x, m.s_z],
        receiver: [m.r_x, m.r_z],
        screen: &screen,
        before: &before,
        middle: &[],
        after: &after,
        z_face_source: HARD,
        z_face_receiver: HARD,
        coh: &coh,
    };
    let scatter = ScreenScatterGeometry {
        r1: m.r1_sm7,
        r2: m.r2_sm7,
        h_e: m.h_e,
        t_air_c: m.t_air_c,
    };

    let mut worst = 0.0_f64;
    for row in &fx.point {
        let dl4 = submodel4(row.f, &cfg).unwrap();
        let c_sr = submodel4_c_sr(row.f, &cfg).unwrap();
        let dl7 = submodel7_delta_l(row.f, &scatter, m.cv2, m.ct2, c_sr).unwrap();
        let combined = combine_scatter(dl4.delta_l_db, dl7);
        let err = (combined - row.delta_l).abs();
        worst = worst.max(err);
        assert!(
            err <= m.tol_db,
            "ΔL₄+ΔL₇({} Hz): engine {:.4} vs oracle {:.4} dB (Δ={:.4})",
            row.f,
            combined,
            row.delta_l,
            err
        );
        // ΔL₄+ΔL₇ must never fall below ΔL₄ (scattering only adds energy).
        assert!(
            combined >= dl4.delta_l_db - 1e-9,
            "scattering lowered the level at {} Hz",
            row.f
        );
    }
    assert!(
        worst <= m.tol_db,
        "worst-case screen-oracle error {worst:.4} dB"
    );
}
