//! Permanent bit-exact regression pinning the PRE-Phase-5 solver output.
//!
//! Phase 5 adds optional seams to `SolveJob` (`forest`, and later `isolation`).
//! The house discipline (D-10/D-12) requires that the ABSENT path
//! (`forest: None`) leave every output bit unchanged. This test captures one
//! canonical `SolveJob`'s `H_coh` (re/im) and `P_incoh_abs` across all 105 bands
//! as raw `f64` bit patterns, committed once from the pre-extension tree, and
//! re-runs the identical job on every build — so any perturbation of the
//! `None` path is a hard, bit-level failure, not an epsilon drift.
//!
//! The comparison is `u64::to_bits()` equality, NOT a float tolerance: the
//! structural-identity contract is exact-or-broken.
//!
//! The committed fixture is captured ONCE, on the pre-extension tree, by the
//! opt-in `regenerate_baseline` generator (ignored by default). It MUST NOT be
//! regenerated after the Phase-5 seams land — doing so would silently redefine
//! the baseline and destroy the regression's meaning.

use envi_engine::freq::{FreqAxis, N_BANDS};
use envi_engine::propagation::air_absorption::Atmosphere;
use envi_engine::propagation::coherence::CoherenceInputs;
use envi_engine::scene::{GroundSegment, TerrainProfile};
use envi_engine::solver::{SolveJob, solve};
use envi_engine::tensor::InMemorySink;
use serde::Deserialize;

const C0: f64 = 340.348;

/// Run the one canonical single-source / single-receiver job (mirroring
/// `mac_identity.rs`'s construction) and return the per-band `f64` bit patterns
/// of `H_coh.re`, `H_coh.im`, and `P_incoh_abs`.
fn compute_baseline() -> (Vec<u64>, Vec<u64>, Vec<u64>) {
    let profile = TerrainProfile::new(
        vec![[2.5, 0.0], [100.0, 0.0]],
        vec![GroundSegment {
            flow_resistivity: 200.0,
            roughness: 0.0,
        }],
    )
    .unwrap();
    let axis = FreqAxis::new();
    let atmos = Atmosphere::new(15.0, 70.0, 101.325).unwrap();
    let coh = CoherenceInputs {
        cv2: 0.0,
        ct2: 0.0,
        t_air_c: 15.0,
        c0: C0,
        roughness_r: 0.0,
        f_delta_nu: 1.0,
        d_m: 97.5,
    };
    let job = SolveJob {
        sub_source: 0,
        receiver: 0,
        profile: &profile,
        src: [2.5, 0.0, 0.5],
        rcv: [100.0, 0.0, 1.5],
        atmosphere: &atmos,
        coh: &coh,
        axis: &axis,
        weather: None,
        directivity_gain_db: None,
        directivity_phase_rad: None,
        forest: None,
        isolation: None,
    };
    let mut sink = InMemorySink::new(1, 1);
    solve([job], 1, 1, &mut sink).unwrap();
    let pair = sink.tensor();

    let mut h_re = Vec::with_capacity(N_BANDS);
    let mut h_im = Vec::with_capacity(N_BANDS);
    let mut p = Vec::with_capacity(N_BANDS);
    for f in 0..N_BANDS {
        let h = pair.h_coh[[0, 0, f]];
        h_re.push(h.re.to_bits());
        h_im.push(h.im.to_bits());
        p.push(pair.p_incoh_abs[[0, 0, f]].to_bits());
    }
    (h_re, h_im, p)
}

#[derive(Deserialize)]
struct Baseline {
    h_re_bits: Vec<String>,
    h_im_bits: Vec<String>,
    p_bits: Vec<String>,
}

const FIXTURE_PATH: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/tests/fixtures/regression/solve_baseline.toml"
);

/// Parse a `0x`-prefixed hex string into the `u64` bit pattern it encodes.
fn parse_bits(s: &str) -> u64 {
    u64::from_str_radix(&s[2..], 16).unwrap_or_else(|_| panic!("bad hex bit pattern: {s}"))
}

/// BASELINE GENERATOR — run ONLY on the pre-extension tree, ONCE.
///
/// `cargo test -p envi-harness --test solve_baseline -- --ignored`
///
/// Writes the committed fixture. DO NOT run this after the Phase-5 seams land:
/// it would redefine the baseline and destroy the `None`-path regression.
#[test]
#[ignore = "baseline generator - run ONLY on the pre-extension tree"]
fn regenerate_baseline() {
    let (h_re, h_im, p) = compute_baseline();
    let fmt = |bits: &[u64]| {
        bits.iter()
            .map(|b| format!("\"{b:#018x}\""))
            .collect::<Vec<_>>()
            .join(", ")
    };
    let mut s = String::new();
    s.push_str("# generated by solve_baseline.rs::regenerate_baseline — DO NOT EDIT\n");
    s.push_str("# Bit-exact pre-extension solver baseline (hex f64 bit patterns per band).\n\n");
    // Top-level arrays MUST precede the [meta] table (TOML captures every key that
    // follows a table header into that table).
    s.push_str(&format!("h_re_bits = [{}]\n", fmt(&h_re)));
    s.push_str(&format!("h_im_bits = [{}]\n", fmt(&h_im)));
    s.push_str(&format!("p_bits = [{}]\n", fmt(&p)));
    s.push('\n');
    s.push_str("[meta]\n");
    s.push_str(
        "description = \"Bit-exact pre-extension solver baseline (hex f64 bit patterns per band)\"\n",
    );
    s.push_str(
        "note = \"captured from the pre-Phase-5 tree — DO NOT REGENERATE; regenerating after the Phase-5 seams land destroys the regression's meaning\"\n",
    );
    std::fs::write(FIXTURE_PATH, s).expect("write solve_baseline.toml");
    eprintln!("wrote {FIXTURE_PATH}");
}

#[test]
fn solver_output_matches_pinned_baseline() {
    let text = std::fs::read_to_string(FIXTURE_PATH).expect("solve_baseline.toml must exist");
    let fx: Baseline = toml::from_str(&text).expect("solve_baseline.toml must parse");
    assert_eq!(
        fx.h_re_bits.len(),
        N_BANDS,
        "baseline must have 105 h_re bits"
    );
    assert_eq!(
        fx.h_im_bits.len(),
        N_BANDS,
        "baseline must have 105 h_im bits"
    );
    assert_eq!(fx.p_bits.len(), N_BANDS, "baseline must have 105 p bits");

    let (h_re, h_im, p) = compute_baseline();
    for f in 0..N_BANDS {
        assert_eq!(
            h_re[f],
            parse_bits(&fx.h_re_bits[f]),
            "band {f}: H_coh.re bits moved — the forest: None path is not bit-identical"
        );
        assert_eq!(
            h_im[f],
            parse_bits(&fx.h_im_bits[f]),
            "band {f}: H_coh.im bits moved — the forest: None path is not bit-identical"
        );
        assert_eq!(
            p[f],
            parse_bits(&fx.p_bits[f]),
            "band {f}: P_incoh_abs bits moved — the forest: None path is not bit-identical"
        );
    }
}
