"""Generate the committed AHN kaartblad tile index for ``envi-gis``.

Writes ``crates/envi-gis/src/registry/ahn_index.toml`` — the tile-name <-> RD New
(EPSG:28992) bbox table that ``envi_gis::tiles::ahn_tiles`` uses to resolve which
whole AHN COG a viewport needs. Committed like the oracle fixtures (08-PATTERNS
"Committed-artifact + no-drift"): the runtime has **no** dependency on the PDOK
ATOM feed, only on this committed artifact.

Source of truth
---------------
The PDOK ATOM feed ``dtm_05m.xml``. Every kaartblad is one ``<link rel="section">``
carrying the download href (the tile name) and a WGS84 ``bbox="w s e n"`` — the
lon/lat ENVELOPE of the tile's RD rectangle.

RD bbox derivation (exact, not the envelope)
--------------------------------------------
Re-projecting the feed's lon/lat envelope back to RD would yield a rectangle a few
hundred metres too large (the RD grid is rotated by up to ~2° against the meridians),
which would over-plan neighbouring tiles near a tile edge. The AHN kaartblad grid is
instead a strict 5000 m x 6250 m RD grid, so this script:

1. projects the feed bbox CENTER to RD (pyproj, EPSG:4326 -> EPSG:28992),
2. snaps that center to the 5000/6250 grid (SW corners land on exact multiples),
3. emits the exact rectangle ``[x, x+5000] x [y, y+6250]``,
4. VERIFIES that re-projecting the snapped rectangle back to WGS84 reproduces the
   feed's bbox to within ``TOL_DEG`` — so a snap that ever went wrong fails loudly
   instead of committing a silently-shifted tile.

Run (dev time only; no Python at test time):

    python tools/gis_oracle/gen_ahn_index.py
"""

from __future__ import annotations

import hashlib
import re
import urllib.request
from pathlib import Path

from pyproj import Transformer

FEED = "https://service.pdok.nl/rws/actueel-hoogtebestand-nederland/atom/dtm_05m.xml"
OUT = Path(__file__).resolve().parents[2] / "crates/envi-gis/src/registry/ahn_index.toml"

TILE_W_M = 5000.0
TILE_H_M = 6250.0
# Max accepted deviation between the snapped rectangle's WGS84 envelope and the
# feed's bbox (degrees). ~0.0005 deg ~= 35 m — well under a tile, far above the
# feed's 6-decimal rounding.
TOL_DEG = 0.0005

LINK_RE = re.compile(
    r'href="[^"]*/dtm_05m/(?P<name>M_[A-Z0-9]+)\.tif"'
    r'[^>]*bbox="(?P<w>[\d.\-]+) (?P<s>[\d.\-]+) (?P<e>[\d.\-]+) (?P<n>[\d.\-]+)"'
)


def fetch_feed() -> str:
    with urllib.request.urlopen(FEED, timeout=120) as resp:  # noqa: S310 (pinned https)
        return resp.read().decode("utf-8")


def main() -> None:
    xml = fetch_feed()
    rows = [m.groupdict() for m in LINK_RE.finditer(xml)]
    if not rows:
        raise SystemExit("no <link rel=section> tile entries found in the feed")

    to_rd = Transformer.from_crs("EPSG:4326", "EPSG:28992", always_xy=True)
    to_wgs = Transformer.from_crs("EPSG:28992", "EPSG:4326", always_xy=True)

    tiles: list[tuple[str, float, float]] = []
    for r in rows:
        w, s, e, n = (float(r["w"]), float(r["s"]), float(r["e"]), float(r["n"]))
        cx, cy = to_rd.transform((w + e) / 2.0, (s + n) / 2.0)
        # Snap the center to the kaartblad grid -> exact SW corner.
        min_x = round((cx - TILE_W_M / 2.0) / TILE_W_M) * TILE_W_M
        min_y = round((cy - TILE_H_M / 2.0) / TILE_H_M) * TILE_H_M

        # Verify: the snapped rectangle's WGS84 envelope must match the feed bbox.
        corners = [
            (min_x, min_y),
            (min_x, min_y + TILE_H_M),
            (min_x + TILE_W_M, min_y),
            (min_x + TILE_W_M, min_y + TILE_H_M),
        ]
        lons, lats = zip(*(to_wgs.transform(x, y) for x, y in corners))
        dev = max(
            abs(min(lons) - w), abs(min(lats) - s), abs(max(lons) - e), abs(max(lats) - n)
        )
        if dev > TOL_DEG:
            raise SystemExit(f"{r['name']}: snapped RD rect deviates {dev:.6f} deg from the feed bbox")
        tiles.append((r["name"], min_x, min_y))

    tiles.sort(key=lambda t: t[0])

    body_lines: list[str] = []
    for name, min_x, min_y in tiles:
        body_lines += [
            "",
            "[[tile]]",
            f'name = "{name}"',
            f"rd_min_x = {min_x:.1f}",
            f"rd_min_y = {min_y:.1f}",
            f"rd_max_x = {min_x + TILE_W_M:.1f}",
            f"rd_max_y = {min_y + TILE_H_M:.1f}",
        ]
    body = "\n".join(body_lines) + "\n"
    digest = hashlib.sha256(body.encode("utf-8")).hexdigest()

    header = f"""# generated by tools/gis_oracle/gen_ahn_index.py — DO NOT EDIT
#
# AHN kaartblad tile index (tile name <-> RD New EPSG:28992 bbox), generated at
# dev time from the PDOK ATOM feed dtm_05m.xml (one <link rel="section"> per tile,
# carrying the tile's download href + its WGS84 envelope). Committed like the
# oracle fixtures (08-PATTERNS "Committed-artifact + no-drift"): there is NO
# runtime dependency on the ATOM feed. The source registry uses a coarse WGS84
# coverage hull to select AHN vs GLO-30; this index resolves the exact kaartblad
# tile name(s) for a whole-tile fetch (08-RESEARCH Pattern 2/3).
#
# This is the COMPLETE grid ({len(tiles)} kaartbladen) — every tile the feed
# publishes. It is NOT a subset: a viewport anywhere inside the AHN coverage hull
# must resolve to a real tile, or the terrain layer plans nothing (the Amsterdam
# regression). Each rectangle is the exact 5000 m x 6250 m kaartblad, obtained by
# snapping the feed bbox center onto the RD grid (see the generator) and verified
# against the feed's WGS84 envelope.
#
# The provenance line below is the sha256 of the [[tile]] body (everything after
# the [meta] table).
[meta]
source = "PDOK ATOM dtm_05m.xml (<link rel=\\"section\\"> per tile)"
crs = "EPSG:28992"
tile_size_m = [{TILE_W_M}, {TILE_H_M}]
tile_count = {len(tiles)}
provenance = "gen_ahn_index.py sha256:{digest}"
"""

    OUT.write_text(header + body, encoding="utf-8")
    print(f"wrote {OUT} — {len(tiles)} tiles, sha256:{digest[:16]}…")


if __name__ == "__main__":
    main()
