"""Generate the committed COG decode oracle fixtures for ``envi-gis``.

Writes a small set of synthetic Cloud-Optimized-GeoTIFF fixtures plus a
per-fixture expected-window TOML under
``crates/envi-gis/tests/fixtures/cog/``. These pin the pure-Rust ``tiff``-crate
decode path (``envi-gis::cog``) against **GDAL** ground truth (via rasterio),
the same committed-oracle pattern as ``tools/crs_oracle/gen_utm.py`` and
``tools/nord2000_oracle``.

The set deliberately spans the format edge cases from 08-RESEARCH:

* ``ahn_bigtiff.tif``      — **BigTIFF** container (AHN analog). First bytes are
  the BigTIFF magic ``49 49 2B 00``; the suite therefore CANNOT pass without
  BigTIFF support (Pitfall 1).
* ``glo30_predictor3.tif`` — DEFLATE + floating-point **predictor 3** (GLO-30
  analog), with non-nominal, non-square pixel sizes so a decoder that assumes a
  nominal grid is caught (Pitfall 5 / A3).
* ``nodata_edge.tif``      — a ``GDAL_NODATA`` sentinel plus dimensions that are
  not a tile multiple, so the bottom/right tiles are **padded beyond
  ImageWidth/Length** (Pitfall 7).
* ``bomb.tif``             — a decompression bomb: large declared IFD dimensions
  vs constant data (a few KB on disk). Exercises the pre-decode ``max_decoded_px``
  budget (threat T-08-02-01); the test passes a small budget so the IFD dwarfs
  it. No expected-window TOML (it is a reject case).

Regeneration is **operator-driven** (``python gen_cog_fixtures.py``): rasterio /
GDAL are a **dev-time install only, NOT a build or test dependency** — the Rust
tests read the committed bytes + TOMLs. Each TOML header records a sha256 of
this generator so a fixture traces to the exact oracle that produced it.
"""

from __future__ import annotations

import hashlib
import math
from pathlib import Path

import numpy as np
import rasterio
from rasterio.transform import Affine
from rasterio.windows import Window

# Output directory (repo-root relative).
HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
OUT = ROOT / "crates/envi-gis/tests/fixtures/cog"

GEN_SHA = hashlib.sha256(Path(__file__).read_bytes()).hexdigest()[:16]
GDAL_VER = rasterio.__gdal_version__
RIO_VER = rasterio.__version__

# Oracle agreement tolerance (f32 round-trip through DEFLATE/predictor is exact,
# but keep a small slack for the predictor-3 byte reshuffle).
TOL = 1e-4


def _fmt(x: float) -> str:
    """Format a float for TOML: exact repr, or the bare ``nan`` token."""
    if isinstance(x, float) and math.isnan(x):
        return "nan"
    return repr(float(x))


def _samples_block(rows: list[list[float]]) -> str:
    """Render a row-major 2-D sample grid as a nested TOML array."""
    inner = ",\n  ".join("[" + ", ".join(_fmt(v) for v in row) + "]" for row in rows)
    return "[\n  " + inner + ",\n]"


def _write_cog(
    name: str,
    data: np.ndarray,
    transform: Affine,
    epsg: int,
    *,
    bigtiff: bool,
    predictor: int,
    nodata: float | None,
    blocksize: int,
) -> Path:
    """Write one tiled DEFLATE GeoTIFF fixture with rasterio/GDAL and return its path."""
    path = OUT / name
    height, width = data.shape
    profile = {
        "driver": "GTiff",
        "dtype": "float32",
        "count": 1,
        "width": width,
        "height": height,
        "crs": rasterio.crs.CRS.from_epsg(epsg),
        "transform": transform,
        "tiled": True,
        "blockxsize": blocksize,
        "blockysize": blocksize,
        "compress": "deflate",
        "predictor": predictor,
        "BIGTIFF": "YES" if bigtiff else "NO",
    }
    if nodata is not None:
        profile["nodata"] = nodata
    with rasterio.open(path, "w", **profile) as dst:
        dst.write(data.astype("float32"), 1)
    return path


def _expected_cases(path: Path, cases: list[dict], nodata: float | None) -> list[dict]:
    """Read each pixel window back from GDAL as ground truth (nodata -> nan)."""
    out = []
    with rasterio.open(path) as src:
        for c in cases:
            win = Window(c["col_off"], c["row_off"], c["win_width"], c["win_height"])
            arr = src.read(1, window=win).astype("float64")
            if nodata is not None:
                arr = np.where(arr == float(nodata), np.nan, arr)
            out.append({**c, "samples": arr.tolist()})
    return out


def _write_toml(
    name: str,
    *,
    fixture: str,
    bigtiff: bool,
    predictor: int,
    width: int,
    height: int,
    transform: Affine,
    nodata: float | None,
    cases: list[dict],
) -> None:
    lines: list[str] = []
    lines.append("# generated by tools/gis_oracle/gen_cog_fixtures.py — DO NOT EDIT")
    lines.append("# COG decode oracle: GDAL (via rasterio) ground truth vs the pure-Rust")
    lines.append("# `tiff` crate decode path in envi-gis::cog. Python is NOT a test dep.")
    lines.append("")
    lines.append("[meta]")
    lines.append(f'oracle = "GDAL {GDAL_VER} via rasterio {RIO_VER}"')
    lines.append(f'provenance = "gen_cog_fixtures.py sha256:{GEN_SHA}"')
    lines.append(f'fixture = "{fixture}"')
    lines.append(f"bigtiff = {'true' if bigtiff else 'false'}")
    lines.append(f"predictor = {predictor}")
    lines.append(f"tol = {_fmt(TOL)}")
    lines.append(f"width = {width}")
    lines.append(f"height = {height}")
    # North-up geotransform derived from ModelPixelScale/ModelTiepoint (Pitfall 5:
    # never assumed — the Rust geo_tags parser must reproduce these exact values).
    lines.append(f"origin_x = {_fmt(transform.c)}")
    lines.append(f"origin_y = {_fmt(transform.f)}")
    lines.append(f"pixel_size_x = {_fmt(transform.a)}")
    lines.append(f"pixel_size_y = {_fmt(transform.e)}")
    lines.append(f"nodata = {_fmt(nodata if nodata is not None else math.nan)}")
    lines.append(f"has_nodata = {'true' if nodata is not None else 'false'}")
    lines.append("")
    for c in cases:
        lines.append("[[case]]")
        lines.append(f'name = "{c["name"]}"')
        lines.append(f"col_off = {c['col_off']}")
        lines.append(f"row_off = {c['row_off']}")
        lines.append(f"win_width = {c['win_width']}")
        lines.append(f"win_height = {c['win_height']}")
        lines.append(f"samples = {_samples_block(c['samples'])}")
        lines.append("")
    (OUT / name).write_text("\n".join(lines) + "\n", encoding="utf-8")


def gen_ahn_bigtiff() -> None:
    """BigTIFF float32 DTM analog: plane z = 10 + 0.5*col + 0.25*row, 64x48 px."""
    width, height = 64, 48
    col = np.arange(width, dtype="float64")[None, :]
    row = np.arange(height, dtype="float64")[:, None]
    data = 10.0 + 0.5 * col + 0.25 * row
    # RD-New-like north-up transform, 0.5 m pixels (AHN 0.5 m raster).
    transform = Affine(0.5, 0.0, 100000.0, 0.0, -0.5, 463000.0)
    path = _write_cog(
        "ahn_bigtiff.tif", data, transform, 28992,
        bigtiff=True, predictor=1, nodata=None, blocksize=16,
    )
    cases = [
        {"name": "interior 4x4", "col_off": 8, "row_off": 12, "win_width": 4, "win_height": 4},
        # Bottom-right corner catches any row/col (x/y) transposition.
        {"name": "bottom-right 3x2", "col_off": 61, "row_off": 46, "win_width": 3, "win_height": 2},
        # Window spanning a tile boundary (tiles are 16 px).
        {"name": "cross-tile 6x6", "col_off": 13, "row_off": 13, "win_width": 6, "win_height": 6},
    ]
    _write_toml(
        "ahn_bigtiff.toml", fixture="ahn_bigtiff.tif", bigtiff=True, predictor=1,
        width=width, height=height, transform=transform, nodata=None,
        cases=_expected_cases(path, cases, None),
    )


def gen_glo30_predictor3() -> None:
    """Classic TIFF, DEFLATE + float predictor 3, non-square non-nominal pixels."""
    width, height = 96, 72
    col = np.arange(width, dtype="float64")[None, :]
    row = np.arange(height, dtype="float64")[:, None]
    # Fractional variation so predictor-3 byte reshuffle is genuinely exercised.
    data = 100.0 + 0.1 * col - 0.07 * row + 0.001 * col * row
    # GLO-30-like geographic transform: longitudinal spacing != latitudinal
    # (Pitfall 5 — the decoder must READ these, not assume 1/3600 square).
    transform = Affine(0.0002777778, 0.0, 4.0, 0.0, -0.0004000000, 52.0)
    path = _write_cog(
        "glo30_predictor3.tif", data, transform, 4326,
        bigtiff=False, predictor=3, nodata=None, blocksize=32,
    )
    cases = [
        {"name": "interior 5x5", "col_off": 10, "row_off": 9, "win_width": 5, "win_height": 5},
        # Spans four 32x32 tiles: exercises predictor-3 decode + tile stitch.
        {"name": "four-tile 8x8", "col_off": 28, "row_off": 28, "win_width": 8, "win_height": 8},
    ]
    _write_toml(
        "glo30_predictor3.toml", fixture="glo30_predictor3.tif", bigtiff=False, predictor=3,
        width=width, height=height, transform=transform, nodata=None,
        cases=_expected_cases(path, cases, None),
    )


def gen_nodata_edge() -> None:
    """Nodata sentinel + edge tiles padded beyond ImageWidth/Length (Pitfall 7)."""
    width, height = 40, 40  # blocksize 32 -> bottom/right tiles padded to 32
    col = np.arange(width, dtype="float64")[None, :]
    row = np.arange(height, dtype="float64")[:, None]
    data = 5.0 + 0.3 * col + 0.2 * row
    nodata = -9999.0
    # Punch a nodata rectangle (a "water body"/coastline hole) at cols 6..10, rows 4..8.
    data[4:9, 6:11] = nodata
    transform = Affine(0.5, 0.0, 100000.0, 0.0, -0.5, 463000.0)
    path = _write_cog(
        "nodata_edge.tif", data, transform, 28992,
        bigtiff=False, predictor=1, nodata=nodata, blocksize=32,
    )
    cases = [
        # Window straddling the nodata rectangle: sentinel cells must become holes.
        {"name": "over-nodata 6x6", "col_off": 5, "row_off": 3, "win_width": 6, "win_height": 6},
        # Bottom-right window landing inside the PADDED edge tiles (cols/rows 32..39):
        # the decoder must crop padding and return only real samples.
        {"name": "padded-edge 8x8", "col_off": 32, "row_off": 32, "win_width": 8, "win_height": 8},
    ]
    _write_toml(
        "nodata_edge.toml", fixture="nodata_edge.tif", bigtiff=False, predictor=1,
        width=width, height=height, transform=transform, nodata=nodata,
        cases=_expected_cases(path, cases, nodata),
    )


def gen_bomb() -> None:
    """Decompression bomb: 2048x2048 declared (4_194_304 px), constant data, KB
    on disk.

    Written block-by-block so peak memory stays ~1 block. The point is the ratio
    of declared IFD pixels to on-disk bytes: the Rust test passes a SMALL
    ``max_decoded_px`` budget and asserts ``decode_window`` rejects it from the
    IFD dimensions BEFORE any ``read_chunk`` — never allocating the full raster
    (threat T-08-02-01). Keeping the declared dims modest keeps the constant
    DEFLATE fixture tiny while the IFD still dwarfs the test budget. No
    expected-window TOML — it is a reject case.
    """
    width = height = 2048
    block = 512
    transform = Affine(30.0, 0.0, 0.0, 0.0, -30.0, 0.0)
    profile = {
        "driver": "GTiff", "dtype": "float32", "count": 1,
        "width": width, "height": height,
        "crs": rasterio.crs.CRS.from_epsg(4326), "transform": transform,
        "tiled": True, "blockxsize": block, "blockysize": block,
        "compress": "deflate", "predictor": 1, "BIGTIFF": "YES",
    }
    const_block = np.full((block, block), 42.0, dtype="float32")
    with rasterio.open(OUT / "bomb.tif", "w", **profile) as dst:
        for r in range(0, height, block):
            for c in range(0, width, block):
                bh = min(block, height - r)
                bw = min(block, width - c)
                dst.write(const_block[:bh, :bw], 1, window=Window(c, r, bw, bh))
    # Minimal meta so the test knows the declared dims without hardcoding.
    lines = [
        "# generated by tools/gis_oracle/gen_cog_fixtures.py — DO NOT EDIT",
        "# Decompression bomb: huge IFD dims, tiny file. Reject-before-decode case.",
        "",
        "[meta]",
        f'provenance = "gen_cog_fixtures.py sha256:{GEN_SHA}"',
        'fixture = "bomb.tif"',
        f"width = {width}",
        f"height = {height}",
        "",
    ]
    (OUT / "bomb.toml").write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    gen_ahn_bigtiff()
    gen_glo30_predictor3()
    gen_nodata_edge()
    gen_bomb()
    total = sum(p.stat().st_size for p in OUT.glob("*.tif"))
    print(f"wrote fixtures to {OUT} (sha256:{GEN_SHA}, GDAL {GDAL_VER})")
    print(f"total .tif bytes: {total} ({total / 1024:.1f} KiB)")


if __name__ == "__main__":
    main()
