"""Generate the committed ground w(z)/Q-hat oracle fixture grid.

Writes ``crates/envi-harness/tests/fixtures/oracle/ground_w_qhat.toml`` — a
cross-implementation reference the Rust engine is tested against. Regeneration
is operator-driven (``python gen_ground_fixtures.py``); the TOML is committed
and Python/scipy are NOT build dependencies.

Provenance: the fixture header records a sha256 of ``common.py`` so a fixture
can be traced to the exact oracle that produced it.
"""

from __future__ import annotations

import hashlib
import math
from pathlib import Path

import common

# Geometry anchor: synthetic flat FORCE-like case (no emission model).
H_S, H_R, D = 0.5, 1.5, 97.5
TAU2, PSI_G = common.geometry_tau2(H_S, H_R, D)

# w(z) grid: all four quadrants + straddling every branch border
# (|x|=3.9, |y|=3, x=6, y=6). Soft ground puts rho_hat in x<0,y>0; hard ground
# in y<0 — both symmetry branches (Eq. 62) must be exercised.
W_POINTS = [
    # Matta-Reichel interior (Q1) anchors
    (0.5, 0.5), (1.0, 1.0), (3.0, 2.0), (2.0, 2.5), (0.1, 0.1),
    # two-pole / three-pole rational branches (Q1)
    (7.0, 1.0), (4.5, 0.5), (1.0, 4.0), (8.0, 8.0), (2.0, 5.0),
    # branch borders (tightly straddled)
    (3.89, 1.0), (3.91, 1.0), (1.0, 2.99), (1.0, 3.01),
    (5.99, 1.0), (6.01, 1.0), (1.0, 5.99), (1.0, 6.01),
    # quadrant 2 (x<0, y>0) — very soft ground at low grazing
    (-0.5, 0.5), (-1.0, 1.0), (-3.0, 2.0), (-4.5, 0.5),
    # quadrant 4 (x>0, y<0) — hard ground
    (0.5, -0.5), (3.0, -2.0), (2.0, -3.0), (4.5, -0.5),
    # quadrant 3 (x<0, y<0)
    (-1.0, -1.0), (-3.0, -2.0),
    # near-real / near-imaginary axes
    (5.0, 0.05), (0.05, 5.0),
]

# Q-hat grid: impedance classes A..H (subset) x FORCE bands, one geometry.
SIGMAS = [12.5, 80.0, 200.0, 2000.0, 20000.0, 200000.0]
FREQS = [63.0, 250.0, 1000.0, 4000.0]


def _fmt(x: float) -> str:
    return repr(float(x))


def main() -> None:
    here = Path(__file__).resolve().parent
    root = here.parents[1]
    out = root / "crates/envi-harness/tests/fixtures/oracle/ground_w_qhat.toml"
    out.parent.mkdir(parents=True, exist_ok=True)

    sha = hashlib.sha256((here / "common.py").read_bytes()).hexdigest()[:16]

    lines: list[str] = []
    lines.append("# generated by tools/nord2000_oracle/gen_ground_fixtures.py — DO NOT EDIT")
    lines.append("# Cross-implementation oracle: scipy.special.wofz + AV 1106/07 Eqs. 57-60.")
    lines.append("")
    lines.append("[meta]")
    lines.append('oracle = "scipy.special.wofz + AV 1106/07 Eqs. 57-60"')
    lines.append(f'provenance = "common.py sha256:{sha}"')
    lines.append(f"c0_m_s = {_fmt(common.C0_M_S)}")
    lines.append(f"h_s = {_fmt(H_S)}")
    lines.append(f"h_r = {_fmt(H_R)}")
    lines.append(f"d = {_fmt(D)}")
    lines.append(f"psi_g_deg = {_fmt(math.degrees(PSI_G))}")
    lines.append(f"tau2_s = {_fmt(TAU2)}")
    # w tolerance 2e-6 (the doc approximation's intrinsic error vs wofz is
    # ~8e-7 relative; 2e-6 covers it with margin — 02-RESEARCH §4).
    lines.append("w_tol_rel = 2e-6")
    lines.append("qhat_tol_rel = 1e-4")
    lines.append("")

    for re, im in W_POINTS:
        w = common.faddeeva_w(complex(re, im))
        lines.append("[[w]]")
        lines.append(f"re = {_fmt(re)}")
        lines.append(f"im = {_fmt(im)}")
        lines.append(f"w_re = {_fmt(w.real)}")
        lines.append(f"w_im = {_fmt(w.imag)}")
        lines.append("")

    for sigma in SIGMAS:
        for f in FREQS:
            z_g = common.ground_impedance(f, sigma)
            q = common.spherical_q(f, TAU2, PSI_G, z_g)
            lines.append("[[qhat]]")
            lines.append(f"sigma = {_fmt(sigma)}")
            lines.append(f"f = {_fmt(f)}")
            lines.append(f"psi_g = {_fmt(PSI_G)}")
            lines.append(f"tau2 = {_fmt(TAU2)}")
            lines.append(f"q_re = {_fmt(q.real)}")
            lines.append(f"q_im = {_fmt(q.imag)}")
            lines.append("")

    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {out} ({len(W_POINTS)} w-points, {len(SIGMAS) * len(FREQS)} qhat-points)")


if __name__ == "__main__":
    main()
