"""Generate the committed Sub-model 11 (reflection effect) oracle fixture.

Writes ``crates/envi-harness/tests/fixtures/oracle/submodel11.toml`` — a
cross-implementation reference for the ENVI Rust engine's
``propagation::terrain_effect::submodel11`` (AV 1106/07 §5.20, Eqs. 296-299 and
the CalcFZd auxiliary Eq. 339). Regeneration is operator-driven
(``python gen_submodel11_fixtures.py``); the TOML is committed and Python/scipy
are NOT build dependencies — the Rust test runs against the committed data alone.

Scope: the reflection-efficiency correction ``L11 = 10·lg(ρE) + 20·lg(Srefl/SFz)``
using the circumscribed-rectangle Fresnel simplification (§5.8) for a vertical
reflector, with the Fresnel half-width from CalcFZd (Eq. 339).

Standing caveat (04-RESEARCH): this oracle re-transcribes the same equations as
the engine, so it cross-checks the IMPLEMENTATION, not the spec reading — there
is no FORCE numeric gate on SM11 (the city cases stay Skipped on the [ASSUMED]
emission coefficients). Equations cited by report + number only (licensing rule).
"""

from __future__ import annotations

import hashlib
import math
from pathlib import Path

import common
import flat_models as fm

F_REFLECTION = 1.0 / 8.0  # §5.8 Fresnel fraction for reflections.
NO_REFLECTION_DB = -300.0
EDGE_TOLERANCE_M = 2.0


def calc_fz_d(r_s, r_r, theta, f_lambda_lambda):
    """CalcFZd (Eq. 339) — Fresnel-zone border distance from O; None if degenerate."""
    r = r_s + r_r
    l = r + f_lambda_lambda
    cos = math.cos(theta)
    a = 4.0 * (l * l - (r * cos) ** 2)
    b = 4.0 * r * cos * (r_r * r_r - r_s * r_s) + 4.0 * (r_s - r_r) * l * l * cos
    c = -(l ** 4) + 2.0 * (r_s * r_s + r_r * r_r) * l * l - (r_s * r_s - r_r * r_r) ** 2
    if abs(a) < 1e-12:
        return None
    disc = b * b - 4.0 * a * c
    if disc < 0.0:
        return None
    return (-b + math.sqrt(disc)) / (2.0 * a)


def submodel11_l11(f_hz, cfg, c0):
    """L11 reflection-efficiency correction (Eq. 296), dB (≤ 0)."""
    if (
        cfg["half_up"] < -EDGE_TOLERANCE_M
        or cfg["half_down"] < -EDGE_TOLERANCE_M
        or cfg["half_left"] < -EDGE_TOLERANCE_M
        or cfg["half_right"] < -EDGE_TOLERANCE_M
    ):
        return NO_REFLECTION_DB
    lam = c0 / f_hz
    b = calc_fz_d(cfg["r_s"], cfg["r_r"], math.pi / 2.0, F_REFLECTION * lam)
    if b is None or not (math.isfinite(b) and b > 0.0):
        return NO_REFLECTION_DB
    vert = max(0.0, min(cfg["half_up"], b)) + max(0.0, min(cfg["half_down"], b))
    horiz = max(0.0, min(cfg["half_left"], b)) + max(0.0, min(cfg["half_right"], b))
    s_refl = vert * horiz
    s_fz = (2.0 * b) * (2.0 * b)
    if not (s_refl > 0.0 and s_fz > 0.0):
        return NO_REFLECTION_DB
    ratio = min(1.0, max(0.0, s_refl / s_fz))
    rho_e = min(1.0, max(0.0, 1.0 - cfg["alpha"]))
    if rho_e <= 0.0:
        return NO_REFLECTION_DB
    return 10.0 * math.log10(rho_e) + 20.0 * math.log10(ratio)


# Reflection configs: a near-perfect large mirror (ρE 1 and 0.7) and a finite
# façade whose size term bites at high frequency (Fresnel zone shrinks with λ).
CONFIGS = [
    {
        "name": "large_mirror_rho1",
        "r_s": 20.0, "r_r": 80.0, "alpha": 0.0,
        "half_up": 100.0, "half_down": 100.0, "half_left": 1000.0, "half_right": 1000.0,
    },
    {
        "name": "large_mirror_rho07",
        "r_s": 20.0, "r_r": 80.0, "alpha": 0.3,
        "half_up": 100.0, "half_down": 100.0, "half_left": 1000.0, "half_right": 1000.0,
    },
    {
        "name": "finite_facade",
        "r_s": 15.0, "r_r": 60.0, "alpha": 0.0,
        "half_up": 6.0, "half_down": 6.0, "half_left": 4.0, "half_right": 4.0,
    },
]

BAND_INDICES = list(range(0, 105, 8))  # 13 bands, 25 Hz … 10 kHz.


def main() -> None:
    axis = fm.freq_axis()
    c0 = common.C0_M_S
    provenance = hashlib.sha256(Path(__file__).read_bytes()).hexdigest()

    out = Path(__file__).resolve().parents[2] / (
        "crates/envi-harness/tests/fixtures/oracle/submodel11.toml"
    )
    lines = [
        "# generated by tools/nord2000_oracle/gen_submodel11_fixtures.py — DO NOT EDIT",
        "# Sub-model 11 reflection effect (AV 1106/07 §5.20, Eqs. 296-299, 339).",
        "",
        "[meta]",
        'oracle = "AV 1106/07 §5.20 transcription (Eq. 296 L11 + Eq. 339 CalcFZd)"',
        f'provenance = "gen_submodel11_fixtures.py sha256:{provenance}"',
        f"c0 = {c0}",
        "# Pure closed-form arithmetic (no wofz); a tight tolerance suffices.",
        "tol_abs_db = 1e-6",
        "",
    ]
    for cfg in CONFIGS:
        bands, vals = [], []
        for bi in BAND_INDICES:
            f = axis[bi]
            bands.append(bi)
            vals.append(submodel11_l11(f, cfg, c0))
        lines.append("[[case]]")
        lines.append(f'name = "{cfg["name"]}"')
        for key in ("r_s", "r_r", "alpha", "half_up", "half_down", "half_left", "half_right"):
            lines.append(f"{key} = {cfg[key]}")
        lines.append(f"band_index = {bands}")
        lines.append("l11_db = [" + ", ".join(f"{v:.10f}" for v in vals) + "]")
        lines.append("")

    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
