"""Generate the committed minimum-phase transmission oracle fixture.

Writes ``crates/envi-harness/tests/fixtures/oracle/minphase.toml`` — a
cross-implementation reference for the ENVI Rust engine's
``propagation::transmission::min_phase_phi_envi`` (the D-06 minimum-phase
isolation filter, an ENVI extension beyond stock Nord2000). Regeneration is
operator-driven (``python gen_minphase_fixtures.py``); the TOML is committed and
Python/numpy are NOT build or test dependencies — the Rust test runs against the
committed data alone.

Algorithm (05-RESEARCH Finding 3a/3e — the engine mirrors this sample-for-sample):
the log-magnitude ``ln|T| = -R*ln10/20`` is even-mirrored to M = 208 samples,
the real cepstrum is taken (``numpy.fft.ifft``), the causal fold is applied
({1, 2x for 1..103, 1 at 104, 0 above}), and the forward transform
(``numpy.fft.fft``) yields ``z``; ``z.imag[:105]`` is the ENVI (e^{+jwt},
lagging) minimum phase. The engine negates it on the Nord2000-native e^{-jwt}
side (explicit negative sine, never a conjugation).

MANDATORY oracle-independence caveat (D-09): this oracle implements the SAME
mirror/fold recipe as the engine, so it cross-checks the IMPLEMENTATION (the DFT
conventions, the fold indices, the sign), NOT the CHOICE of recipe. The recipe's
correctness as a minimum-phase reconstruction is pinned independently by the
analytic verification in 05-RESEARCH 3a/3b (the known minimum-phase system
H = 1 + 0.5*e^{-jw} reproduced to 6.7e-16) and by the engine's T3 causality
property test. The numpy recipe below is used precisely because it shares the
engine's exact sample layout; the scipy Hilbert helper (different sample layout,
odd N, no mirror) is NOT equivalent and is deliberately not used.
"""

from __future__ import annotations

import hashlib
import math
from pathlib import Path

import numpy as np

N_BANDS = 105
G = 10.0 ** (3.0 / 10.0)  # IEC 61260-1 base-10 octave ratio.


def freq_axis() -> np.ndarray:
    """105 exact 1/12-octave centres: 1000 * G^((i-64)/12), i = 0..104."""
    return np.array([1000.0 * G ** ((i - 64) / 12.0) for i in range(N_BANDS)])


def min_phase_envi(r_db: np.ndarray) -> np.ndarray:
    """ENVI (e^{+jwt}, lagging) minimum phase from R(f) — the engine's twin."""
    ln_mag = -r_db * np.log(10.0) / 20.0
    y = np.concatenate([ln_mag, ln_mag[-2:0:-1]])  # even mirror, M = 208
    c = np.fft.ifft(y)  # real cepstrum
    fold = np.zeros(len(y))
    fold[0] = 1.0
    fold[1 : len(y) // 2] = 2.0
    fold[len(y) // 2] = 1.0
    z = np.fft.fft(c * fold)
    return z.imag[:N_BANDS]  # native e^{-jwt} phase = -this (engine negates)


def flat_30() -> np.ndarray:
    """Spectrally flat 30 dB partition — a pure real attenuation (phi == 0)."""
    return np.full(N_BANDS, 30.0)


def mass_law_ramp() -> np.ndarray:
    """A +6 dB/octave mass-law-shaped rising R, clipped >= 0 (live phase)."""
    f = freq_axis()
    return np.maximum(0.0, 20.0 * np.log10(f / 50.0))


def bumpy() -> np.ndarray:
    """A plausible measured-looking spectrum: two band-index sinusoids, offset >0."""
    n = np.arange(N_BANDS, dtype=float)
    return 30.0 + 8.0 * np.sin(0.15 * n) + 5.0 * np.sin(0.05 * n + 1.0)


def notch() -> np.ndarray:
    """A narrow dip at mid-band (stress case), staying >= 0."""
    n = np.arange(N_BANDS, dtype=float)
    return 40.0 - 30.0 * np.exp(-(((n - 52.0) / 3.0) ** 2))


CASES = [
    ("flat_30", flat_30()),
    ("mass_law_ramp", mass_law_ramp()),
    ("bumpy", bumpy()),
    ("notch", notch()),
]


def _fmt(arr: np.ndarray) -> str:
    # repr(float(...)) is round-trip exact — Rust parses back the identical f64.
    return "[" + ", ".join(repr(float(v)) for v in arr) + "]"


def main() -> None:
    provenance = hashlib.sha256(Path(__file__).read_bytes()).hexdigest()
    out = Path(__file__).resolve().parents[2] / (
        "crates/envi-harness/tests/fixtures/oracle/minphase.toml"
    )
    lines = [
        "# generated by tools/nord2000_oracle/gen_minphase_fixtures.py — DO NOT EDIT",
        "# Minimum-phase isolation filter (ENG-10 + D-06 ENVI extension).",
        "# phi_envi_rad is the ENVI e^{+jwt} lagging phase; the engine's native",
        "# e^{-jwt} filter negates it (explicit negative sine, no conjugation).",
        "",
        "[meta]",
        'oracle = "numpy.fft even-mirror real-cepstrum min-phase (05-RESEARCH Finding 3a/3e)"',
        f'provenance = "gen_minphase_fixtures.py sha256:{provenance}"',
        "# Naive-DFT (engine) vs FFT (oracle) round-off is ~1e-13; margin for libm.",
        "tol_abs_rad = 1e-9",
        "",
    ]
    for name, r in CASES:
        phi = min_phase_envi(r)
        if not np.all(np.isfinite(r)) or np.any(r < 0.0):
            raise ValueError(f"case {name}: R must be finite and >= 0 for all bands")
        lines.append("[[case]]")
        lines.append(f'name = "{name}"')
        lines.append(f"r_db = {_fmt(r)}")
        lines.append(f"phi_envi_rad = {_fmt(phi)}")
        lines.append("")

    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
