"""Generate the committed flat-terrain ground-effect oracle fixtures.

Writes two 105-point ΔL_t curves the Rust engine is cross-checked against:

  * ``flat_sigma200.toml``      — uniform σ=200 (class D), zero turbulence; the
                                  case-1-like homogeneous geometry (Sub-model 1).
  * ``flat_mixed_case21.toml``  — the FORCE case-21 flat mixed road/grass layout
                                  (road σ=20000 / grass σ=200 alternating, two
                                  types over four strips), with Fc ACTIVE
                                  (Cv²=0.12, CT²=0.008, FΔν=1) — Sub-model 2.

Regeneration is operator-driven (``python gen_flat_fixtures.py``); the TOML is
committed and Python/scipy are NOT build dependencies. The fixtures carry a
sha256 provenance of ``flat_models.py`` + ``common.py``.
"""

from __future__ import annotations

import hashlib
from pathlib import Path

import common
import flat_models as fm

C0 = common.C0_M_S
H_S, H_R, D = 0.5, 1.5, 97.5

# FORCE case-21 flat mixed layout: road (G, σ=20000) / grass (D, σ=200)
# alternating — four strips, two surface types (research Pitfall 3).
CASE21_STRIPS = [
    {"x0": 0.0, "x1": 10.0, "sigma": 20000.0, "rough": 0.0},
    {"x0": 10.0, "x1": 50.0, "sigma": 200.0, "rough": 0.0},
    {"x0": 50.0, "x1": 60.0, "sigma": 20000.0, "rough": 0.0},
    {"x0": 60.0, "x1": 97.5, "sigma": 200.0, "rough": 0.0},
]
CV2, CT2 = 0.12, 0.008  # forced turbulence even at u=0 (FORCE parameter audit)


def _fmt(x: float) -> str:
    return repr(float(x))


def _provenance() -> str:
    here = Path(__file__).resolve().parent
    h = hashlib.sha256()
    for name in ("common.py", "flat_models.py"):
        h.update((here / name).read_bytes())
    return h.hexdigest()[:16]


def _header(name: str, kind: str, extra: list[str]) -> list[str]:
    # Flat top-level keys (no [table] header) so `bands` stays top-level — a
    # trailing `[meta]` table would capture `bands` as `meta.bands`.
    lines = [
        "# generated by tools/nord2000_oracle/gen_flat_fixtures.py — DO NOT EDIT",
        "# Cross-implementation oracle: scipy.special.wofz + AV 1106/07 Eqs. 115-133.",
        "",
        f'name = "{name}"',
        f'kind = "{kind}"',
        'oracle = "scipy.special.wofz + AV 1106/07 flat ground effect"',
        f'provenance = "common.py+flat_models.py sha256:{_provenance()}"',
        "tolerance_db = 0.1",
        f"c0_m_s = {_fmt(C0)}",
        f"h_s = {_fmt(H_S)}",
        f"h_r = {_fmt(H_R)}",
        f"d = {_fmt(D)}",
        *extra,
        "",
    ]
    return lines


def main() -> None:
    here = Path(__file__).resolve().parent
    root = here.parents[1]
    out_dir = root / "crates/envi-harness/tests/fixtures/oracle"
    out_dir.mkdir(parents=True, exist_ok=True)
    axis = fm.freq_axis()

    # Shared per-profile globals for the oracle (rho_sep + Fc distance).
    fm.HEIGHTS = (H_S, H_R)
    fm.DIST_D = D

    # 1) Uniform σ=200 via Sub-model 1, zero turbulence.
    rays = fm.straight_rays(D, H_S, H_R, C0)
    lines = _header(
        "flat ground, sigma=200 (class D), hs=0.5, hr=1.5, d=97.5, F=Ff only",
        "ground-effect-sm1",
        ['sigma = 200.0', "cv2 = 0.0", "ct2 = 0.0"],
    )
    bands = []
    for f in axis:
        h_coh, p_incoh = fm.submodel1(f, rays, 200.0, C0)
        bands.append(fm.delta_l_db(h_coh, p_incoh))
    lines.append("bands = [")
    for v in bands:
        lines.append(f"  {_fmt(v)},")
    lines.append("]")
    (out_dir / "flat_sigma200.toml").write_text("\n".join(lines) + "\n", encoding="utf-8")

    # 2) Mixed case-21 via Sub-model 2 with Fc active.
    lines = _header(
        "FORCE case-21 flat mixed road(G,20000)/grass(D,200), 4 strips / 2 types",
        "ground-effect-sm2",
        ["cv2 = 0.12", "ct2 = 0.008", "sigma_road = 20000.0", "sigma_grass = 200.0"],
    )
    bands = []
    for f in axis:
        h_coh, p_incoh = fm.submodel2(f, CASE21_STRIPS, D, H_S, H_R, C0, CV2, CT2, 15.0)
        bands.append(fm.delta_l_db(h_coh, p_incoh))
    lines.append("bands = [")
    for v in bands:
        lines.append(f"  {_fmt(v)},")
    lines.append("]")
    (out_dir / "flat_mixed_case21.toml").write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"wrote flat_sigma200.toml + flat_mixed_case21.toml ({len(axis)} points each)")


if __name__ == "__main__":
    main()
