//! Cross-implementation CRS oracle test (06-RESEARCH §Pattern 1, house oracle
//! pattern 06-PATTERNS §10c).
//!
//! Loads the committed `tests/fixtures/oracle/utm_landmarks.toml` — generated by
//! `tools/crs_oracle/gen_utm.py` from **pyproj** (the C PROJ library) — and
//! asserts that `envi-geo`'s pure-Rust `proj4rs` transforms match the PROJ
//! ground truth to `<= tol_m` (1e-3 m) on ~10 world-spread landmarks. This
//! discharges the A1 accuracy assumption (GEOX-04, SC3) empirically: a proj4rs
//! `etmerc` discrepancy shows up here as a fixture mismatch.
//!
//! **Python/pyproj are NOT needed at test time** — the TOML is committed data.

use envi_geo::{LonLat, ProjectCrs, utm_zone_for};
use serde::Deserialize;

#[derive(Deserialize)]
struct Fixtures {
    meta: Meta,
    case: Vec<Case>,
}

#[derive(Deserialize)]
struct Meta {
    /// Oracle agreement tolerance, meters (read from the fixture, never hardcoded).
    tol_m: f64,
}

#[derive(Deserialize)]
struct Case {
    name: String,
    lon_deg: f64,
    lat_deg: f64,
    zone: u8,
    south: bool,
    easting_m: f64,
    northing_m: f64,
}

fn load() -> Fixtures {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/fixtures/oracle/utm_landmarks.toml"
    );
    let text = std::fs::read_to_string(path).expect("oracle fixture TOML must exist");
    toml::from_str(&text).expect("oracle fixture TOML must parse")
}

#[test]
fn envi_geo_matches_pyproj_oracle() {
    let fx = load();
    assert!(
        fx.case.len() >= 10,
        "oracle fixture must have >= 10 cases (fixture truncation guard), got {}",
        fx.case.len()
    );

    let (mut saw_north, mut saw_south) = (false, false);

    for c in &fx.case {
        let ll = LonLat {
            lon_deg: c.lon_deg,
            lat_deg: c.lat_deg,
        };

        // (a) zone selection agrees with the fixture (same plain formula).
        assert_eq!(
            utm_zone_for(ll).expect("valid landmark"),
            c.zone,
            "{}: zone mismatch",
            c.name
        );

        let crs = ProjectCrs::from_zone(c.zone, c.south).expect("valid zone");

        // (b) forward transform matches the PROJ easting/northing within tol_m.
        let xy = crs.to_utm(ll).expect("forward transform");
        let de = (xy.x_m - c.easting_m).abs();
        let dn = (xy.y_m - c.northing_m).abs();
        assert!(
            de <= fx.meta.tol_m && dn <= fx.meta.tol_m,
            "{}: proj4rs vs pyproj disagree — d_easting {de:.2e} m, d_northing {dn:.2e} m (tol {:.1e} m)",
            c.name,
            fx.meta.tol_m
        );

        // (c) round-trip back to WGS84 lands within 1e-6 deg of the input.
        let back = crs.to_wgs84(xy).expect("inverse transform");
        assert!(
            (back.lon_deg - c.lon_deg).abs() <= 1e-6 && (back.lat_deg - c.lat_deg).abs() <= 1e-6,
            "{}: round-trip drifted — got ({}, {}) vs ({}, {})",
            c.name,
            back.lon_deg,
            back.lat_deg,
            c.lon_deg,
            c.lat_deg
        );

        saw_north |= !c.south;
        saw_south |= c.south;
    }

    assert!(
        saw_north && saw_south,
        "fixture must cover both hemispheres (north: {saw_north}, south: {saw_south})"
    );
}
