//! Cross-implementation RD New (EPSG:28992) oracle test.
//!
//! Loads the committed `tests/fixtures/oracle/rd_landmarks.toml` — generated by
//! `tools/crs_oracle/gen_rd.py` from **pyproj** (the C PROJ library) — and
//! asserts that `envi-geo`'s pure-Rust `proj4rs` RD New transform matches the
//! PROJ ground truth to `<= tol_m` (1.0 m) on Netherlands-spread landmarks, in
//! both directions. This discharges the DATA-01 accuracy requirement (GEOX-04)
//! empirically: a proj4rs `sterea` / `towgs84` discrepancy shows up here as a
//! fixture mismatch, and the `cargo test` gate fails if envi-geo drifts.
//!
//! **Python/pyproj are NOT needed at test time** — the TOML is committed data.

use envi_geo::{LonLat, RdNewCrs, SceneXY};
use serde::Deserialize;

#[derive(Deserialize)]
struct Fixtures {
    meta: Meta,
    case: Vec<Case>,
}

#[derive(Deserialize)]
struct Meta {
    /// Oracle agreement tolerance, meters (read from the fixture, never hardcoded).
    tol_m: f64,
}

#[derive(Deserialize)]
struct Case {
    name: String,
    lon_deg: f64,
    lat_deg: f64,
    rd_x_m: f64,
    rd_y_m: f64,
}

fn load() -> Fixtures {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/fixtures/oracle/rd_landmarks.toml"
    );
    let text = std::fs::read_to_string(path).expect("RD oracle fixture TOML must exist");
    toml::from_str(&text).expect("RD oracle fixture TOML must parse")
}

/// Meter error between two WGS84 points (small-angle) — lets the inverse
/// direction be compared in meters against the same `tol_m`.
fn error_m(a: LonLat, b: LonLat) -> f64 {
    let dlat_m = (a.lat_deg - b.lat_deg).abs() * 111_320.0;
    let dlon_m = (a.lon_deg - b.lon_deg).abs() * 111_320.0 * a.lat_deg.to_radians().cos();
    (dlat_m.powi(2) + dlon_m.powi(2)).sqrt()
}

#[test]
fn envi_geo_matches_pyproj_rd_oracle() {
    let fx = load();
    assert!(
        fx.case.len() >= 6,
        "RD oracle fixture must have >= 6 cases (fixture truncation guard), got {}",
        fx.case.len()
    );

    let crs = RdNewCrs::new().expect("valid RD New CRS");
    let mut saw_amersfoort = false;

    for c in &fx.case {
        let ll = LonLat {
            lon_deg: c.lon_deg,
            lat_deg: c.lat_deg,
        };

        // (a) forward transform matches the PROJ RD easting/northing within tol_m.
        let rd = crs.to_rd(ll).expect("forward WGS84 -> RD");
        let dx = (rd.x_m - c.rd_x_m).abs();
        let dy = (rd.y_m - c.rd_y_m).abs();
        assert!(
            dx <= fx.meta.tol_m && dy <= fx.meta.tol_m,
            "{}: proj4rs vs pyproj disagree — d_x {dx:.3} m, d_y {dy:.3} m (tol {} m)",
            c.name,
            fx.meta.tol_m
        );

        // (b) inverse transform of the PROJ RD coordinate lands within tol_m of
        // the input lon/lat (measured in meters).
        let back = crs
            .to_wgs84(SceneXY {
                x_m: c.rd_x_m,
                y_m: c.rd_y_m,
            })
            .expect("inverse RD -> WGS84");
        let inv_err = error_m(ll, back);
        assert!(
            inv_err <= fx.meta.tol_m,
            "{}: inverse drifted {inv_err:.3} m from input (tol {} m)",
            c.name,
            fx.meta.tol_m
        );

        saw_amersfoort |= c.name.contains("Amersfoort");
    }

    // Coverage: the Amersfoort datum point (RD false origin) must be pinned.
    assert!(
        saw_amersfoort,
        "RD oracle fixture must include the Amersfoort datum landmark"
    );
}
